package com.loyaltyworks.hrjohnson.model

import com.squareup.moshi.JsonClass

import com.squareup.moshi.Json
import java.io.Serializable


@JsonClass(generateAdapter = true)
data class IdentityExistencyRequest(
    @Json(name = "ActionType")
    var actionType: Int? = null,
    @Json(name = "ActorId")
    var actorId: Int? = null,
    @Json(name = "Location")
    var location: LocationExistency? = null
)

@JsonClass(generateAdapter = true)
data class LocationExistency(
    @Json(name = "BillingTypeID")
    var billingTypeID: Int? = null,
    @Json(name = "ProductID") 
    var productID: Int? = null,
    @Json(name = "UserName")
    var userName: String? = null
)

@JsonClass(generateAdapter = true)
data class IdentityExistencyResponse(
    @Json(name = "returnMessage") 
    var returnMessage: Any? = null,
    @Json(name = "returnValue") 
    var returnValue: Int? = null,
    @Json(name = "totalRecords") 
    var totalRecords: Int? = null
)

@JsonClass(generateAdapter = true)
data class BusinessDealerRequest(
    @Json(name = "ActionType") 
    val actionType: Int? = null,
    @Json(name = "ActorId") 
    val actorId: String? = null
)


@JsonClass(generateAdapter = true)
data class BusinessDealerResponse(
    @Json(name = "audienceOptimizationId") 
    val audienceOptimizationId: Any? = null,
    @Json(name = "bindYearWiseAttendanceList") 
    val bindYearWiseAttendanceList: Any? = null,
    @Json(name = "customerBasicInfoList") 
    val customerBasicInfoList: Any? = null,
    @Json(name = "customerFamilyList") 
    val customerFamilyList: Any? = null,
    @Json(name = "customerMappingList") 
    val customerMappingList: Any? = null,
    @Json(name = "customerOptimizationDetailsList") 
    val customerOptimizationDetailsList: Any? = null,
    @Json(name = "customerPreferenceList") 
    val customerPreferenceList: Any? = null,
    @Json(name = "distributorlst") 
    val distributorlst: List<Distributorlst>? = null,
    @Json(name = "expiredReferalCount") 
    val expiredReferalCount: Int? = null,
    @Json(name = "hierarchyMapDetails") 
    val hierarchyMapDetails: Any? = null,
    @Json(name = "hierarchyMapDetailsList") 
    val hierarchyMapDetailsList: Any? = null,
    @Json(name = "lstCustomer") 
    val lstCustomer: List<Any>? = null,
    @Json(name = "lstCustomerEntityMapping") 
    val lstCustomerEntityMapping: Any? = null,
    @Json(name = "lstCustomerIdentityInfo") 
    val lstCustomerIdentityInfo: Any? = null,
    @Json(name = "lstCustomerOfficalInfo") 
    val lstCustomerOfficalInfo: Any? = null,
    @Json(name = "lstCustomerPaymentModeDetails") 
    val lstCustomerPaymentModeDetails: Any? = null,
    @Json(name = "lstCustomerRemarksHistory") 
    val lstCustomerRemarksHistory: Any? = null,
    @Json(name = "lstCustomerSearchDetails") 
    val lstCustomerSearchDetails: Any? = null,
    @Json(name = "lstRewardTransDetails") 
    val lstRewardTransDetails: Any? = null,
    @Json(name = "lstRewardTransactionBasedonProduct") 
    val lstRewardTransactionBasedonProduct: Any? = null,
    @Json(name = "lstVehicleDetails") 
    val lstVehicleDetails: Any? = null,
    @Json(name = "lstWorkSiteInfoDetails") 
    val lstWorkSiteInfoDetails: Any? = null,
    @Json(name = "mappedCustomersList") 
    val mappedCustomersList: Any? = null,
    @Json(name = "mappedProductList") 
    val mappedProductList: Any? = null,
    @Json(name = "objCustomer") 
    val objCustomer: Any? = null,
    @Json(name = "objCustomerDetails") 
    val objCustomerDetails: Any? = null,
    @Json(name = "objCustomerOfficalInfo") 
    val objCustomerOfficalInfo: Any? = null,
    @Json(name = "pendingReferalCount") 
    val pendingReferalCount: Int? = null,
    @Json(name = "pointBal") 
    val pointBal: Any? = null,
    @Json(name = "retailerlst") 
    val retailerlst: List<Retailerlst>? = null,
    @Json(name = "returnMessage") 
    val returnMessage: Any? = null,
    @Json(name = "returnValue") 
    val returnValue: Int? = null,
    @Json(name = "subscriptionDetails") 
    val subscriptionDetails: Any? = null,
    @Json(name = "succcessReferealCount") 
    val succcessReferealCount: Int? = null,
    @Json(name = "totEarned") 
    val totEarned: Any? = null,
    @Json(name = "totPointExpired") 
    val totPointExpired: Any? = null,
    @Json(name = "totRedeem") 
    val totRedeem: Any? = null,
    @Json(name = "totSalesReturn") 
    val totSalesReturn: Any? = null,
    @Json(name = "totalRecords") 
    val totalRecords: Int? = null,
    @Json(name = "totalWithDrawls") 
    val totalWithDrawls: Int? = null
)

@JsonClass(generateAdapter = true)
data class Distributorlst(
    @Json(name = "accountComStatus") 
    val accountComStatus: Int? = null,
    @Json(name = "accountNumber") 
    val accountNumber: Any? = null,
    @Json(name = "accountStatus") 
    val accountStatus: Any? = null,
    @Json(name = "accountStatusId") 
    val accountStatusId: Int? = null,
    @Json(name = "accountType") 
    val accountType: Any? = null,
    @Json(name = "accountTypeId") 
    val accountTypeId: Int? = null,
    @Json(name = "acountHolderName") 
    val acountHolderName: Any? = null,
    @Json(name = "actionType") 
    val actionType: Int? = null,
    @Json(name = "actorId") 
    val actorId: Int? = null,
    @Json(name = "actorRole") 
    val actorRole: Any? = null,
    @Json(name = "address") 
    val address: Any? = null,
    @Json(name = "address1") 
    val address1: String? = null,
    @Json(name = "address2") 
    val address2: Any? = null,
    @Json(name = "addressId") 
    val addressId: Int? = null,
    @Json(name = "addressLatitude") 
    val addressLatitude: Any? = null,
    @Json(name = "addressLongitude") 
    val addressLongitude: Any? = null,
    @Json(name = "anniversary") 
    val anniversary: String? = null,
    @Json(name = "areaId") 
    val areaId: Int? = null,
    @Json(name = "areaName") 
    val areaName: Any? = null,
    @Json(name = "autoAccountType") 
    val autoAccountType: Any? = null,
    @Json(name = "autoBankCounty") 
    val autoBankCounty: Any? = null,
    @Json(name = "avgRunningPerMonth") 
    val avgRunningPerMonth: Double? = null,
    @Json(name = "bankAccountVerifiedStatus") 
    val bankAccountVerifiedStatus: Int? = null,
    @Json(name = "bankAddress") 
    val bankAddress: Any? = null,
    @Json(name = "bankBranch") 
    val bankBranch: Any? = null,
    @Json(name = "bankCity") 
    val bankCity: Any? = null,
    @Json(name = "bankCode") 
    val bankCode: Any? = null,
    @Json(name = "bankCountryID") 
    val bankCountryID: Int? = null,
    @Json(name = "bankCurrencyID") 
    val bankCurrencyID: Int? = null,
    @Json(name = "bankIbanNumber") 
    val bankIbanNumber: Any? = null,
    @Json(name = "bankName") 
    val bankName: Any? = null,
    @Json(name = "bankPassbookImage") 
    val bankPassbookImage: Any? = null,
    @Json(name = "bankPostCode") 
    val bankPostCode: Any? = null,
    @Json(name = "bankRoutingNumber") 
    val bankRoutingNumber: Any? = null,
    @Json(name = "bankSwiftCode") 
    val bankSwiftCode: Any? = null,
    @Json(name = "book_App_Date") 
    val bookAppDate: String? = null,
    @Json(name = "branchCode") 
    val branchCode: Any? = null,
    @Json(name = "chassisNumber") 
    val chassisNumber: Any? = null,
    @Json(name = "cityId") 
    val cityId: Int? = null,
    @Json(name = "cityName") 
    val cityName: Any? = null,
    @Json(name = "company") 
    val company: Any? = null,
    @Json(name = "contactID") 
    val contactID: Int? = null,
    @Json(name = "contactName") 
    val contactName: Any? = null,
    @Json(name = "contactPhone") 
    val contactPhone: Any? = null,
    @Json(name = "contractFileName") 
    val contractFileName: Any? = null,
    @Json(name = "contractId") 
    val contractId: Int? = null,
    @Json(name = "contractName") 
    val contractName: Any? = null,
    @Json(name = "countryId") 
    val countryId: Int? = null,
    @Json(name = "countryName") 
    val countryName: Any? = null,
    @Json(name = "createdBy") 
    val createdBy: Any? = null,
    @Json(name = "createdDate") 
    val createdDate: String? = null,
    @Json(name = "currency") 
    val currency: Any? = null,
    @Json(name = "custAccountType") 
    val custAccountType: Any? = null,
    @Json(name = "customerCategory") 
    val customerCategory: Any? = null,
    @Json(name = "customerCategoryId") 
    val customerCategoryId: Int? = null,
    @Json(name = "customerCityId") 
    val customerCityId: Int? = null,
    @Json(name = "customerDob") 
    val customerDob: Any? = null,
    @Json(name = "customerEmail") 
    val customerEmail: Any? = null,
    @Json(name = "customerGrade") 
    val customerGrade: Any? = null,
    @Json(name = "customer_Grade_ID") 
    val customerGradeID: Int? = null,
    @Json(name = "customerId") 
    val customerId: Int? = null,
    @Json(name = "customerIsActive") 
    val customerIsActive: Boolean? = null,
    @Json(name = "customerMenuId") 
    val customerMenuId: Any? = null,
    @Json(name = "customerMobile") 
    val customerMobile: Any? = null,
    @Json(name = "customerOrderCount") 
    val customerOrderCount: Int? = null,
    @Json(name = "customerRelationshipId") 
    val customerRelationshipId: Int? = null,
    @Json(name = "customerRewardCardBalance") 
    val customerRewardCardBalance: Int? = null,
    @Json(name = "customerRewardPoints") 
    val customerRewardPoints: Int? = null,
    @Json(name = "customerStateId") 
    val customerStateId: Int? = null,
    @Json(name = "customerType") 
    val customerType: String? = null,
    @Json(name = "customerTypeID") 
    val customerTypeID: Int? = null,
    @Json(name = "customerTypeId") 
    val customerTypeId: Int? = null,
    @Json(name = "customerZip") 
    val customerZip: Any? = null,
    @Json(name = "customersRemarks") 
    val customersRemarks: Any? = null,
    @Json(name = "dateOfSale") 
    val dateOfSale: String? = null,
    @Json(name = "debitedGiftCardAmount") 
    val debitedGiftCardAmount: Double? = null,
    @Json(name = "departmentId") 
    val departmentId: Int? = null,
    @Json(name = "designation") 
    val designation: Any? = null,
    @Json(name = "designationId") 
    val designationId: Int? = null,
    @Json(name = "displayImage") 
    val displayImage: Any? = null,
    @Json(name = "district") 
    val district: Any? = null,
    @Json(name = "districtId") 
    val districtId: Int? = null,
    @Json(name = "districtName") 
    val districtName: Any? = null,
    @Json(name = "dob") 
    val dob: String? = null,
    @Json(name = "domain") 
    val domain: Any? = null,
    @Json(name = "drivenBy") 
    val drivenBy: Any? = null,
    @Json(name = "email") 
    val email: Any? = null,
    @Json(name = "encashBalance") 
    val encashBalance: Int? = null,
    @Json(name = "engineNumber") 
    val engineNumber: Any? = null,
    @Json(name = "enrolledBy") 
    val enrolledBy: Any? = null,
    @Json(name = "enrollmentBonus") 
    val enrollmentBonus: Int? = null,
    @Json(name = "enrollmentId") 
    val enrollmentId: Any? = null,
    @Json(name = "enrollmentReferenceDate") 
    val enrollmentReferenceDate: String? = null,
    @Json(name = "enrollmentReferenceNumber") 
    val enrollmentReferenceNumber: Any? = null,
    @Json(name = "enrollmentStatus") 
    val enrollmentStatus: Boolean? = null,
    @Json(name = "financeEmailId") 
    val financeEmailId: Any? = null,
    @Json(name = "financeName") 
    val financeName: Any? = null,
    @Json(name = "financeUserName") 
    val financeUserName: Any? = null,
    @Json(name = "financialDate") 
    val financialDate: Any? = null,
    @Json(name = "firstName") 
    val firstName: String? = null,
    @Json(name = "fromDate") 
    val fromDate: String? = null,
    @Json(name = "frontofficeExecutive") 
    val frontofficeExecutive: Any? = null,
    @Json(name = "gender") 
    val gender: Any? = null,
    @Json(name = "giftCardAmount") 
    val giftCardAmount: Double? = null,
    @Json(name = "giftedGiftCardAmount") 
    val giftedGiftCardAmount: Double? = null,
    @Json(name = "giftedPoints") 
    val giftedPoints: Int? = null,
    @Json(name = "gstNumber") 
    val gstNumber: Any? = null,
    @Json(name = "identificationNo") 
    val identificationNo: Any? = null,
    @Json(name = "identificationTypeID") 
    val identificationTypeID: Int? = null,
    @Json(name = "ifscCode") 
    val ifscCode: Any? = null,
    @Json(name = "image") 
    val image: Any? = null,
    @Json(name = "incorporationDate") 
    val incorporationDate: String? = null,
    @Json(name = "industryId") 
    val industryId: Int? = null,
    @Json(name = "insuranceExpDate") 
    val insuranceExpDate: String? = null,
    @Json(name = "insuranceRenewalAmount") 
    val insuranceRenewalAmount: Int? = null,
    @Json(name = "invoiceAmount") 
    val invoiceAmount: Any? = null,
    @Json(name = "invoiceNo") 
    val invoiceNo: Any? = null,
    @Json(name = "isActive") 
    val isActive: Boolean? = null,
    @Json(name = "isBankPassbookNewImage") 
    val isBankPassbookNewImage: Boolean? = null,
    @Json(name = "isBlackListed") 
    val isBlackListed: Boolean? = null,
    @Json(name = "isCCVerified") 
    val isCCVerified: Boolean? = null,
    @Json(name = "isDriverChanging") 
    val isDriverChanging: Any? = null,
    @Json(name = "isF2FMeeting") 
    val isF2FMeeting: Boolean? = null,
    @Json(name = "isGradeVerified") 
    val isGradeVerified: Boolean? = null,
    @Json(name = "isIDUploaded") 
    val isIDUploaded: Boolean? = null,
    @Json(name = "isNameUpdated") 
    val isNameUpdated: Boolean? = null,
    @Json(name = "isProfilePictureUploaded") 
    val isProfilePictureUploaded: Boolean? = null,
    @Json(name = "isSemiUpdated") 
    val isSemiUpdated: Boolean? = null,
    @Json(name = "isSiteVerified") 
    val isSiteVerified: Boolean? = null,
    @Json(name = "isUpdatePassword") 
    val isUpdatePassword: Boolean? = null,
    @Json(name = "isVerified") 
    val isVerified: Int? = null,
    @Json(name = "isVinChassis_Active") 
    val isVinChassisActive: Any? = null,
    @Json(name = "issuedGiftCardAmount") 
    val issuedGiftCardAmount: Double? = null,
    @Json(name = "jAnniversary") 
    val jAnniversary: Any? = null,
    @Json(name = "jBook_App_Date") 
    val jBookAppDate: Any? = null,
    @Json(name = "jCreatedDate") 
    val jCreatedDate: Any? = null,
    @Json(name = "jD_InvoiceDate") 
    val jDInvoiceDate: String? = null,
    @Json(name = "jD_InvoiceNo") 
    val jDInvoiceNo: Any? = null,
    @Json(name = "jDateOfSale") 
    val jDateOfSale: Any? = null,
    @Json(name = "jEnrollmentReferenceDate") 
    val jEnrollmentReferenceDate: Any? = null,
    @Json(name = "jInsuranceExpDate") 
    val jInsuranceExpDate: Any? = null,
    @Json(name = "jNomineeDOB") 
    val jNomineeDOB: Any? = null,
    @Json(name = "jPolicyDate") 
    val jPolicyDate: Any? = null,
    @Json(name = "jdob") 
    val jdob: Any? = null,
    @Json(name = "jjD_InvoiceDate") 
    val jjDInvoiceDate: Any? = null,
    @Json(name = "laborAmount") 
    val laborAmount: Int? = null,
    @Json(name = "landlineNumber") 
    val landlineNumber: Any? = null,
    @Json(name = "landmark") 
    val landmark: Any? = null,
    @Json(name = "language") 
    val language: Any? = null,
    @Json(name = "languageId") 
    val languageId: Int? = null,
    @Json(name = "lastActive") 
    val lastActive: Any? = null,
    @Json(name = "lastName") 
    val lastName: Any? = null,
    @Json(name = "locality") 
    val locality: Any? = null,
    @Json(name = "locationCode") 
    val locationCode: Any? = null,
    @Json(name = "locationId") 
    val locationId: Int? = null,
    @Json(name = "locationName") 
    val locationName: Any? = null,
    @Json(name = "loyaltyId") 
    val loyaltyId: String? = null,
    @Json(name = "loyaltyIdAutoGen") 
    val loyaltyIdAutoGen: Boolean? = null,
    @Json(name = "memberSince") 
    val memberSince: Any? = null,
    @Json(name = "merchantId") 
    val merchantId: Int? = null,
    @Json(name = "merchantName") 
    val merchantName: Any? = null,
    @Json(name = "mobile") 
    val mobile: Any? = null,
    @Json(name = "mobileNumberLimitation") 
    val mobileNumberLimitation: Int? = null,
    @Json(name = "mobilePrefix") 
    val mobilePrefix: Any? = null,
    @Json(name = "mobile_Two") 
    val mobileTwo: Any? = null,
    @Json(name = "modelNumber") 
    val modelNumber: Any? = null,
    @Json(name = "nativeCountryId") 
    val nativeCountryId: Int? = null,
    @Json(name = "nativeStateId") 
    val nativeStateId: Int? = null,
    @Json(name = "nfcTagID") 
    val nfcTagID: Any? = null,
    @Json(name = "nominee") 
    val nominee: Any? = null,
    @Json(name = "nomineeDOB") 
    val nomineeDOB: String? = null,
    @Json(name = "panStatus") 
    val panStatus: Any? = null,
    @Json(name = "panStatusId") 
    val panStatusId: Int? = null,
    @Json(name = "parentCustomerId") 
    val parentCustomerId: Int? = null,
    @Json(name = "password") 
    val password: Any? = null,
    @Json(name = "payOut") 
    val payOut: Int? = null,
    @Json(name = "payload") 
    val payload: Any? = null,
    @Json(name = "pointBalance") 
    val pointBalance: Int? = null,
    @Json(name = "pointExpired") 
    val pointExpired: Int? = null,
    @Json(name = "policyDate") 
    val policyDate: String? = null,
    @Json(name = "policyNumber") 
    val policyNumber: Any? = null,
    @Json(name = "postInternalNote") 
    val postInternalNote: Any? = null,
    @Json(name = "presentKM") 
    val presentKM: Double? = null,
    @Json(name = "profilePicture") 
    val profilePicture: Any? = null,
    @Json(name = "pushId") 
    val pushId: Any? = null,
    @Json(name = "recipientPhonenumber") 
    val recipientPhonenumber: Any? = null,
    @Json(name = "recipientType") 
    val recipientType: Any? = null,
    @Json(name = "referedBy") 
    val referedBy: Any? = null,
    @Json(name = "referralCode") 
    val referralCode: Any? = null,
    @Json(name = "referrerCode") 
    val referrerCode: Any? = null,
    @Json(name = "refundGiftCardAmount") 
    val refundGiftCardAmount: Double? = null,
    @Json(name = "regStatus") 
    val regStatus: Int? = null,
    @Json(name = "regStatusId") 
    val regStatusId: Int? = null,
    @Json(name = "regType") 
    val regType: Any? = null,
    @Json(name = "registrationSource") 
    val registrationSource: Int? = null,
    @Json(name = "relateD_PROJECT_TYPE") 
    val relateDPROJECTTYPE: Any? = null,
    @Json(name = "relationship") 
    val relationship: Any? = null,
    @Json(name = "remarks") 
    val remarks: Any? = null,
    @Json(name = "rewardPoint") 
    val rewardPoint: Double? = null,
    @Json(name = "rewardPoints") 
    val rewardPoints: Int? = null,
    @Json(name = "roleID") 
    val roleID: Int? = null,
    @Json(name = "sapNo") 
    val sapNo: Any? = null,
    @Json(name = "searchText") 
    val searchText: Any? = null,
    @Json(name = "sourceOfLogin") 
    val sourceOfLogin: Any? = null,
    @Json(name = "spouseDOB") 
    val spouseDOB: String? = null,
    @Json(name = "spouseName") 
    val spouseName: Any? = null,
    @Json(name = "sscEmailId") 
    val sscEmailId: Any? = null,
    @Json(name = "sscName") 
    val sscName: Any? = null,
    @Json(name = "sscUserName") 
    val sscUserName: Any? = null,
    @Json(name = "stateId") 
    val stateId: Int? = null,
    @Json(name = "stateName") 
    val stateName: Any? = null,
    @Json(name = "subscriptionDurationID") 
    val subscriptionDurationID: Int? = null,
    @Json(name = "talukId") 
    val talukId: Int? = null,
    @Json(name = "talukName") 
    val talukName: Any? = null,
    @Json(name = "targetCreditPeriod") 
    val targetCreditPeriod: Int? = null,
    @Json(name = "targetValue") 
    val targetValue: Int? = null,
    @Json(name = "taxId") 
    val taxId: Any? = null,
    @Json(name = "tehsilBlockMandal") 
    val tehsilBlockMandal: Any? = null,
    @Json(name = "title") 
    val title: Any? = null,
    @Json(name = "toDate") 
    val toDate: String? = null,
    @Json(name = "token") 
    val token: Any? = null,
    @Json(name = "totalCollection") 
    val totalCollection: Int? = null,
    @Json(name = "totalNetValue") 
    val totalNetValue: Int? = null,
    @Json(name = "tradeLicence") 
    val tradeLicence: Any? = null,
    @Json(name = "userId") 
    val userId: Int? = null,
    @Json(name = "userName") 
    val userName: Any? = null,
    @Json(name = "vehicleID") 
    val vehicleID: Int? = null,
    @Json(name = "vehicleNumber") 
    val vehicleNumber: Any? = null,
    @Json(name = "vehicleType") 
    val vehicleType: Any? = null,
    @Json(name = "vendorCode") 
    val vendorCode: Any? = null,
    @Json(name = "verifiedStatus") 
    val verifiedStatus: Any? = null,
    @Json(name = "village") 
    val village: Any? = null,
    @Json(name = "walletName") 
    val walletName: Any? = null,
    @Json(name = "walletNumber") 
    val walletNumber: Any? = null,
    @Json(name = "walletVerifiedStatus") 
    val walletVerifiedStatus: Boolean? = null,
    @Json(name = "whatsAppNumber") 
    val whatsAppNumber: Any? = null,
    @Json(name = "zip") 
    val zip: Any? = null
)

@JsonClass(generateAdapter = true)
data class Retailerlst(
    @Json(name = "accountComStatus") 
    val accountComStatus: Int? = null,
    @Json(name = "accountNumber") 
    val accountNumber: Any? = null,
    @Json(name = "accountStatus") 
    val accountStatus: Any? = null,
    @Json(name = "accountStatusId") 
    val accountStatusId: Int? = null,
    @Json(name = "accountType") 
    val accountType: Any? = null,
    @Json(name = "accountTypeId") 
    val accountTypeId: Int? = null,
    @Json(name = "acountHolderName") 
    val acountHolderName: Any? = null,
    @Json(name = "actionType") 
    val actionType: Int? = null,
    @Json(name = "actorId") 
    val actorId: Int? = null,
    @Json(name = "actorRole") 
    val actorRole: Any? = null,
    @Json(name = "address") 
    val address: Any? = null,
    @Json(name = "address1") 
    val address1: String? = null,
    @Json(name = "address2") 
    val address2: Any? = null,
    @Json(name = "addressId") 
    val addressId: Int? = null,
    @Json(name = "addressLatitude") 
    val addressLatitude: Any? = null,
    @Json(name = "addressLongitude") 
    val addressLongitude: Any? = null,
    @Json(name = "anniversary") 
    val anniversary: String? = null,
    @Json(name = "areaId") 
    val areaId: Int? = null,
    @Json(name = "areaName") 
    val areaName: Any? = null,
    @Json(name = "autoAccountType") 
    val autoAccountType: Any? = null,
    @Json(name = "autoBankCounty") 
    val autoBankCounty: Any? = null,
    @Json(name = "avgRunningPerMonth") 
    val avgRunningPerMonth: Double? = null,
    @Json(name = "bankAccountVerifiedStatus") 
    val bankAccountVerifiedStatus: Int? = null,
    @Json(name = "bankAddress") 
    val bankAddress: Any? = null,
    @Json(name = "bankBranch") 
    val bankBranch: Any? = null,
    @Json(name = "bankCity") 
    val bankCity: Any? = null,
    @Json(name = "bankCode") 
    val bankCode: Any? = null,
    @Json(name = "bankCountryID") 
    val bankCountryID: Int? = null,
    @Json(name = "bankCurrencyID") 
    val bankCurrencyID: Int? = null,
    @Json(name = "bankIbanNumber") 
    val bankIbanNumber: Any? = null,
    @Json(name = "bankName") 
    val bankName: Any? = null,
    @Json(name = "bankPassbookImage") 
    val bankPassbookImage: Any? = null,
    @Json(name = "bankPostCode") 
    val bankPostCode: Any? = null,
    @Json(name = "bankRoutingNumber") 
    val bankRoutingNumber: Any? = null,
    @Json(name = "bankSwiftCode") 
    val bankSwiftCode: Any? = null,
    @Json(name = "book_App_Date") 
    val bookAppDate: String? = null,
    @Json(name = "branchCode") 
    val branchCode: Any? = null,
    @Json(name = "chassisNumber") 
    val chassisNumber: Any? = null,
    @Json(name = "cityId") 
    val cityId: Int? = null,
    @Json(name = "cityName") 
    val cityName: Any? = null,
    @Json(name = "company") 
    val company: Any? = null,
    @Json(name = "contactID") 
    val contactID: Int? = null,
    @Json(name = "contactName") 
    val contactName: Any? = null,
    @Json(name = "contactPhone") 
    val contactPhone: Any? = null,
    @Json(name = "contractFileName") 
    val contractFileName: Any? = null,
    @Json(name = "contractId") 
    val contractId: Int? = null,
    @Json(name = "contractName") 
    val contractName: Any? = null,
    @Json(name = "countryId") 
    val countryId: Int? = null,
    @Json(name = "countryName") 
    val countryName: Any? = null,
    @Json(name = "createdBy") 
    val createdBy: Any? = null,
    @Json(name = "createdDate") 
    val createdDate: String? = null,
    @Json(name = "currency") 
    val currency: Any? = null,
    @Json(name = "custAccountType") 
    val custAccountType: Any? = null,
    @Json(name = "customerCategory") 
    val customerCategory: Any? = null,
    @Json(name = "customerCategoryId") 
    val customerCategoryId: Int? = null,
    @Json(name = "customerCityId") 
    val customerCityId: Int? = null,
    @Json(name = "customerDob") 
    val customerDob: Any? = null,
    @Json(name = "customerEmail") 
    val customerEmail: Any? = null,
    @Json(name = "customerGrade") 
    val customerGrade: Any? = null,
    @Json(name = "customer_Grade_ID") 
    val customerGradeID: Int? = null,
    @Json(name = "customerId") 
    val customerId: Int? = null,
    @Json(name = "customerIsActive") 
    val customerIsActive: Boolean? = null,
    @Json(name = "customerMenuId") 
    val customerMenuId: Any? = null,
    @Json(name = "customerMobile") 
    val customerMobile: Any? = null,
    @Json(name = "customerOrderCount") 
    val customerOrderCount: Int? = null,
    @Json(name = "customerRelationshipId") 
    val customerRelationshipId: Int? = null,
    @Json(name = "customerRewardCardBalance") 
    val customerRewardCardBalance: Int? = null,
    @Json(name = "customerRewardPoints") 
    val customerRewardPoints: Int? = null,
    @Json(name = "customerStateId") 
    val customerStateId: Int? = null,
    @Json(name = "customerType") 
    val customerType: String? = null,
    @Json(name = "customerTypeID") 
    val customerTypeID: Int? = null,
    @Json(name = "customerTypeId") 
    val customerTypeId: Int? = null,
    @Json(name = "customerZip") 
    val customerZip: Any? = null,
    @Json(name = "customersRemarks") 
    val customersRemarks: Any? = null,
    @Json(name = "dateOfSale") 
    val dateOfSale: String? = null,
    @Json(name = "debitedGiftCardAmount") 
    val debitedGiftCardAmount: Double? = null,
    @Json(name = "departmentId") 
    val departmentId: Int? = null,
    @Json(name = "designation") 
    val designation: Any? = null,
    @Json(name = "designationId") 
    val designationId: Int? = null,
    @Json(name = "displayImage") 
    val displayImage: Any? = null,
    @Json(name = "district") 
    val district: Any? = null,
    @Json(name = "districtId") 
    val districtId: Int? = null,
    @Json(name = "districtName") 
    val districtName: Any? = null,
    @Json(name = "dob") 
    val dob: String? = null,
    @Json(name = "domain") 
    val domain: Any? = null,
    @Json(name = "drivenBy") 
    val drivenBy: Any? = null,
    @Json(name = "email") 
    val email: Any? = null,
    @Json(name = "encashBalance") 
    val encashBalance: Int? = null,
    @Json(name = "engineNumber") 
    val engineNumber: Any? = null,
    @Json(name = "enrolledBy") 
    val enrolledBy: Any? = null,
    @Json(name = "enrollmentBonus") 
    val enrollmentBonus: Int? = null,
    @Json(name = "enrollmentId") 
    val enrollmentId: Any? = null,
    @Json(name = "enrollmentReferenceDate") 
    val enrollmentReferenceDate: String? = null,
    @Json(name = "enrollmentReferenceNumber") 
    val enrollmentReferenceNumber: Any? = null,
    @Json(name = "enrollmentStatus") 
    val enrollmentStatus: Boolean? = null,
    @Json(name = "financeEmailId") 
    val financeEmailId: Any? = null,
    @Json(name = "financeName") 
    val financeName: Any? = null,
    @Json(name = "financeUserName") 
    val financeUserName: Any? = null,
    @Json(name = "financialDate") 
    val financialDate: Any? = null,
    @Json(name = "firstName") 
    val firstName: String? = null,
    @Json(name = "fromDate") 
    val fromDate: String? = null,
    @Json(name = "frontofficeExecutive") 
    val frontofficeExecutive: Any? = null,
    @Json(name = "gender") 
    val gender: Any? = null,
    @Json(name = "giftCardAmount") 
    val giftCardAmount: Double? = null,
    @Json(name = "giftedGiftCardAmount") 
    val giftedGiftCardAmount: Double? = null,
    @Json(name = "giftedPoints") 
    val giftedPoints: Int? = null,
    @Json(name = "gstNumber") 
    val gstNumber: Any? = null,
    @Json(name = "identificationNo") 
    val identificationNo: Any? = null,
    @Json(name = "identificationTypeID") 
    val identificationTypeID: Int? = null,
    @Json(name = "ifscCode") 
    val ifscCode: Any? = null,
    @Json(name = "image") 
    val image: Any? = null,
    @Json(name = "incorporationDate") 
    val incorporationDate: String? = null,
    @Json(name = "industryId") 
    val industryId: Int? = null,
    @Json(name = "insuranceExpDate") 
    val insuranceExpDate: String? = null,
    @Json(name = "insuranceRenewalAmount") 
    val insuranceRenewalAmount: Int? = null,
    @Json(name = "invoiceAmount") 
    val invoiceAmount: Any? = null,
    @Json(name = "invoiceNo") 
    val invoiceNo: Any? = null,
    @Json(name = "isActive") 
    val isActive: Boolean? = null,
    @Json(name = "isBankPassbookNewImage") 
    val isBankPassbookNewImage: Boolean? = null,
    @Json(name = "isBlackListed") 
    val isBlackListed: Boolean? = null,
    @Json(name = "isCCVerified") 
    val isCCVerified: Boolean? = null,
    @Json(name = "isDriverChanging") 
    val isDriverChanging: Any? = null,
    @Json(name = "isF2FMeeting") 
    val isF2FMeeting: Boolean? = null,
    @Json(name = "isGradeVerified") 
    val isGradeVerified: Boolean? = null,
    @Json(name = "isIDUploaded") 
    val isIDUploaded: Boolean? = null,
    @Json(name = "isNameUpdated") 
    val isNameUpdated: Boolean? = null,
    @Json(name = "isProfilePictureUploaded") 
    val isProfilePictureUploaded: Boolean? = null,
    @Json(name = "isSemiUpdated") 
    val isSemiUpdated: Boolean? = null,
    @Json(name = "isSiteVerified") 
    val isSiteVerified: Boolean? = null,
    @Json(name = "isUpdatePassword") 
    val isUpdatePassword: Boolean? = null,
    @Json(name = "isVerified") 
    val isVerified: Int? = null,
    @Json(name = "isVinChassis_Active") 
    val isVinChassisActive: Any? = null,
    @Json(name = "issuedGiftCardAmount") 
    val issuedGiftCardAmount: Double? = null,
    @Json(name = "jAnniversary") 
    val jAnniversary: Any? = null,
    @Json(name = "jBook_App_Date") 
    val jBookAppDate: Any? = null,
    @Json(name = "jCreatedDate") 
    val jCreatedDate: Any? = null,
    @Json(name = "jD_InvoiceDate") 
    val jDInvoiceDate: String? = null,
    @Json(name = "jD_InvoiceNo") 
    val jDInvoiceNo: Any? = null,
    @Json(name = "jDateOfSale") 
    val jDateOfSale: Any? = null,
    @Json(name = "jEnrollmentReferenceDate") 
    val jEnrollmentReferenceDate: Any? = null,
    @Json(name = "jInsuranceExpDate") 
    val jInsuranceExpDate: Any? = null,
    @Json(name = "jNomineeDOB") 
    val jNomineeDOB: Any? = null,
    @Json(name = "jPolicyDate") 
    val jPolicyDate: Any? = null,
    @Json(name = "jdob") 
    val jdob: Any? = null,
    @Json(name = "jjD_InvoiceDate") 
    val jjDInvoiceDate: Any? = null,
    @Json(name = "laborAmount") 
    val laborAmount: Int? = null,
    @Json(name = "landlineNumber") 
    val landlineNumber: Any? = null,
    @Json(name = "landmark") 
    val landmark: Any? = null,
    @Json(name = "language") 
    val language: Any? = null,
    @Json(name = "languageId") 
    val languageId: Int? = null,
    @Json(name = "lastActive") 
    val lastActive: Any? = null,
    @Json(name = "lastName") 
    val lastName: Any? = null,
    @Json(name = "locality") 
    val locality: Any? = null,
    @Json(name = "locationCode") 
    val locationCode: Any? = null,
    @Json(name = "locationId") 
    val locationId: Int? = null,
    @Json(name = "locationName") 
    val locationName: Any? = null,
    @Json(name = "loyaltyId") 
    val loyaltyId: String? = null,
    @Json(name = "loyaltyIdAutoGen") 
    val loyaltyIdAutoGen: Boolean? = null,
    @Json(name = "memberSince") 
    val memberSince: Any? = null,
    @Json(name = "merchantId") 
    val merchantId: Int? = null,
    @Json(name = "merchantName") 
    val merchantName: Any? = null,
    @Json(name = "mobile") 
    val mobile: Any? = null,
    @Json(name = "mobileNumberLimitation") 
    val mobileNumberLimitation: Int? = null,
    @Json(name = "mobilePrefix") 
    val mobilePrefix: Any? = null,
    @Json(name = "mobile_Two") 
    val mobileTwo: Any? = null,
    @Json(name = "modelNumber") 
    val modelNumber: Any? = null,
    @Json(name = "nativeCountryId") 
    val nativeCountryId: Int? = null,
    @Json(name = "nativeStateId") 
    val nativeStateId: Int? = null,
    @Json(name = "nfcTagID") 
    val nfcTagID: Any? = null,
    @Json(name = "nominee") 
    val nominee: Any? = null,
    @Json(name = "nomineeDOB") 
    val nomineeDOB: String? = null,
    @Json(name = "panStatus") 
    val panStatus: Any? = null,
    @Json(name = "panStatusId") 
    val panStatusId: Int? = null,
    @Json(name = "parentCustomerId") 
    val parentCustomerId: Int? = null,
    @Json(name = "password") 
    val password: Any? = null,
    @Json(name = "payOut") 
    val payOut: Int? = null,
    @Json(name = "payload") 
    val payload: Any? = null,
    @Json(name = "pointBalance") 
    val pointBalance: Int? = null,
    @Json(name = "pointExpired") 
    val pointExpired: Int? = null,
    @Json(name = "policyDate") 
    val policyDate: String? = null,
    @Json(name = "policyNumber") 
    val policyNumber: Any? = null,
    @Json(name = "postInternalNote") 
    val postInternalNote: Any? = null,
    @Json(name = "presentKM") 
    val presentKM: Double? = null,
    @Json(name = "profilePicture") 
    val profilePicture: Any? = null,
    @Json(name = "pushId") 
    val pushId: Any? = null,
    @Json(name = "recipientPhonenumber") 
    val recipientPhonenumber: Any? = null,
    @Json(name = "recipientType") 
    val recipientType: Any? = null,
    @Json(name = "referedBy") 
    val referedBy: Any? = null,
    @Json(name = "referralCode") 
    val referralCode: Any? = null,
    @Json(name = "referrerCode") 
    val referrerCode: Any? = null,
    @Json(name = "refundGiftCardAmount") 
    val refundGiftCardAmount: Double? = null,
    @Json(name = "regStatus") 
    val regStatus: Int? = null,
    @Json(name = "regStatusId") 
    val regStatusId: Int? = null,
    @Json(name = "regType") 
    val regType: Any? = null,
    @Json(name = "registrationSource") 
    val registrationSource: Int? = null,
    @Json(name = "relateD_PROJECT_TYPE") 
    val relateDPROJECTTYPE: Any? = null,
    @Json(name = "relationship") 
    val relationship: Any? = null,
    @Json(name = "remarks") 
    val remarks: Any? = null,
    @Json(name = "rewardPoint") 
    val rewardPoint: Double? = null,
    @Json(name = "rewardPoints") 
    val rewardPoints: Int? = null,
    @Json(name = "roleID") 
    val roleID: Int? = null,
    @Json(name = "sapNo") 
    val sapNo: Any? = null,
    @Json(name = "searchText") 
    val searchText: Any? = null,
    @Json(name = "sourceOfLogin") 
    val sourceOfLogin: Any? = null,
    @Json(name = "spouseDOB") 
    val spouseDOB: String? = null,
    @Json(name = "spouseName") 
    val spouseName: Any? = null,
    @Json(name = "sscEmailId") 
    val sscEmailId: Any? = null,
    @Json(name = "sscName") 
    val sscName: Any? = null,
    @Json(name = "sscUserName") 
    val sscUserName: Any? = null,
    @Json(name = "stateId") 
    val stateId: Int? = null,
    @Json(name = "stateName") 
    val stateName: Any? = null,
    @Json(name = "subscriptionDurationID") 
    val subscriptionDurationID: Int? = null,
    @Json(name = "talukId") 
    val talukId: Int? = null,
    @Json(name = "talukName") 
    val talukName: Any? = null,
    @Json(name = "targetCreditPeriod") 
    val targetCreditPeriod: Int? = null,
    @Json(name = "targetValue") 
    val targetValue: Int? = null,
    @Json(name = "taxId") 
    val taxId: Any? = null,
    @Json(name = "tehsilBlockMandal") 
    val tehsilBlockMandal: Any? = null,
    @Json(name = "title") 
    val title: Any? = null,
    @Json(name = "toDate") 
    val toDate: String? = null,
    @Json(name = "token") 
    val token: Any? = null,
    @Json(name = "totalCollection") 
    val totalCollection: Int? = null,
    @Json(name = "totalNetValue") 
    val totalNetValue: Int? = null,
    @Json(name = "tradeLicence") 
    val tradeLicence: Any? = null,
    @Json(name = "userId") 
    val userId: Int? = null,
    @Json(name = "userName") 
    val userName: Any? = null,
    @Json(name = "vehicleID") 
    val vehicleID: Int? = null,
    @Json(name = "vehicleNumber") 
    val vehicleNumber: Any? = null,
    @Json(name = "vehicleType") 
    val vehicleType: Any? = null,
    @Json(name = "vendorCode") 
    val vendorCode: Any? = null,
    @Json(name = "verifiedStatus") 
    val verifiedStatus: Any? = null,
    @Json(name = "village") 
    val village: Any? = null,
    @Json(name = "walletName") 
    val walletName: Any? = null,
    @Json(name = "walletNumber") 
    val walletNumber: Any? = null,
    @Json(name = "walletVerifiedStatus") 
    val walletVerifiedStatus: Boolean? = null,
    @Json(name = "whatsAppNumber") 
    val whatsAppNumber: Any? = null,
    @Json(name = "zip") 
    val zip: Any? = null
)

//save other proff request
@JsonClass(generateAdapter = true)
data class IdentityRequest(
    @Json(name = "ActionType")
    var actionType: String? = null,
    @Json(name = "ActorId")
    var actorId: String? = null,
    @Json(name = "lstIdentityInfo")
    var lstIdentityInfo: List<LstIdentityInfo?>? = null,
    @Json(name = "ObjCustomerJson")
    var objCustomerJson: OtherProffobjCustomerJson? = null
)

@JsonClass(generateAdapter = true)
data class LstIdentityInfo(
    @Json(name = "IdentityDocument")
    var identityDocument: String? = null,
    @Json(name = "IdentityDocumentBack")
    var identityDocumentBack: String? = null,
    @Json(name = "IdentityID")
    var identityID: Int? = null,
    @Json(name = "IdentityNo")
    var identityNo: String? = null,
    @Json(name = "IdentityType")
    var identityType: Int? = null,
    @Json(name = "IsNewIdentity")
    var isNewIdentity: Int? = null,
    @Json(name = "IsNewIdentityBack")
    var isNewIdentityBack: Int? = null
)

@JsonClass(generateAdapter = true)
 data  class OtherProffobjCustomerJson(
    @Json(name = "customerTypeID")
    var customerTypeID: Int? = null,
    @Json(name = "loyaltyId")
    var loyaltyId: String? = null
)


//save other proof response
@JsonClass(generateAdapter = true)
data class IdentityResponse(
    @Json(name = "lstCustomer")
    var lstCustomer: Any? = null,
    @Json(name = "returnMessage")
    var returnMessage: String? = null,
    @Json(name = "returnValue")
    var returnValue: Int? = null,
    @Json(name = "totalRecords")
    var totalRecords: Int? = null
)




/*Get Customer Details for Aadhar */
@JsonClass(generateAdapter = true)
data class GetCustomerDetailsRequest(
    @Json(name = "ActionType") 
    val actionType: Int? = null,
    @Json(name = "CustomerId") 
    val customerId: Int? = null
)



@JsonClass(generateAdapter = true)
data class GetCustomerDetailsResponse(
    @Json(name = "customerBasicInfoList")
    var customerBasicInfoList: List<Any?>? = null,
    @Json(name = "customerFamilyList")
    var customerFamilyList: List<Any?>? = null,
    @Json(name = "customerPreferenceList")
    var customerPreferenceList: List<Any?>? = null,
    @Json(name = "hierarchyMapDetails")
    var hierarchyMapDetails: HierarchyMapDetails? = null,
    @Json(name = "lstCustomerIdentityInfo")
    var lstCustomerIdentityInfo: List<LstCustomerIdentityInfo?>? = null,
    @Json(name = "lstCustomerJson")
    var lstCustomerJson: Any? = null,
    @Json(name = "lstCustomerOfficalInfoJson")
    var lstCustomerOfficalInfoJson: Any? = null,
    @Json(name = "lstVehicleJson")
    var lstVehicleJson: Any? = null,
    @Json(name = "lstWorkSiteInfoDetails")
    var lstWorkSiteInfoDetails: Any? = null,
    @Json(name = "mappedProductList")
    var mappedProductList: List<Any?>? = null,
    @Json(name = "objCustomer")
    var objCustomer: ObjCustomerrr? = null,
    @Json(name = "objCustomerDetails")
    var objCustomerDetails: ObjCustomerDetailssss? = null,
    @Json(name = "objCustomerOfficalInfo")
    var objCustomerOfficalInfo: ObjCustomerOfficalInfooo? = null,
    @Json(name = "pdf")
    var pdf: Any? = null,
    @Json(name = "returnMessage")
    var returnMessage: Any? = null,
    @Json(name = "returnValue")
    var returnValue: Int? = null,
    @Json(name = "subscriptionDetails")
    var subscriptionDetails: Any? = null,
    @Json(name = "totalRecords")
    var totalRecords: Int? = null
)

@JsonClass(generateAdapter = true)
data class HierarchyMapDetails(
    @Json(name = "asmName")
    var asmName: Any? = null,
    @Json(name = "customerType")
    var customerType: Any? = null,
    @Json(name = "customerUserID")
    var customerUserID: Int? = null,
    @Json(name = "customerUserName")
    var customerUserName: Any? = null,
    @Json(name = "hieracMasterMapID")
    var hieracMasterMapID: Int? = null,
    @Json(name = "locationID")
    var locationID: Int? = null,
    @Json(name = "locationName")
    var locationName: Any? = null,
    @Json(name = "parentUserID")
    var parentUserID: Int? = null,
    @Json(name = "seMobileNo")
    var seMobileNo: Any? = null,
    @Json(name = "seName")
    var seName: Any? = null,
    @Json(name = "user2UserID")
    var user2UserID: Int? = null,
    @Json(name = "userUserID")
    var userUserID: Int? = null,
    @Json(name = "userUseruName")
    var userUseruName: Any? = null
)

@JsonClass(generateAdapter = true)
data class LstCustomerIdentityInfo(
    @Json(name = "identityDocument")
    var identityDocument: String? = null,
    @Json(name = "identityDocumentBack")
    var identityDocumentBack: String? = null,
    @Json(name = "identityID")
    var identityID: Int? = null,
    @Json(name = "identityName")
    var identityName: Any? = null,
    @Json(name = "identityNo")
    var identityNo: String? = null,
    @Json(name = "identityType")
    var identityType: String? = null,
    @Json(name = "identityTypeID")
    var identityTypeID: Int? = null,
    @Json(name = "isNewIdentity")
    var isNewIdentity: Boolean? = null,
    @Json(name = "isNewIdentityBack")
    var isNewIdentityBack: Boolean? = null,
    @Json(name = "panCardNO")
    var panCardNO: Any? = null,
    @Json(name = "remarks")
    var remarks: String? = null,
    @Json(name = "verficationStatus")
    var verficationStatus: Int? = null,
): Serializable

@JsonClass(generateAdapter = true)
data class ObjCustomerrr(
    @Json(name = "aadharNumber")
    var aadharNumber: Any? = null,
    @Json(name = "accountComStatus")
    var accountComStatus: Int? = null,
    @Json(name = "accountNumber")
    var accountNumber: Any? = null,
    @Json(name = "accountStatus")
    var accountStatus: Any? = null,
    @Json(name = "accountType")
    var accountType: Any? = null,
    @Json(name = "accountTypeID")
    var accountTypeID: Int? = null,
    @Json(name = "acountHolderName")
    var acountHolderName: Any? = null,
    @Json(name = "address1")
    var address1: String? = null,
    @Json(name = "address2")
    var address2: String? = null,
    @Json(name = "addressId")
    var addressId: Int? = null,
    @Json(name = "addressLatitude")
    var addressLatitude: Any? = null,
    @Json(name = "addressLongitude")
    var addressLongitude: Any? = null,
    @Json(name = "ageGroupId")
    var ageGroupId: Int? = null,
    @Json(name = "anniversary")
    var anniversary: Any? = null,
    @Json(name = "areaId")
    var areaId: Int? = null,
    @Json(name = "areaName")
    var areaName: Any? = null,
    @Json(name = "autoAccountType")
    var autoAccountType: Any? = null,
    @Json(name = "autoBankCounty")
    var autoBankCounty: Any? = null,
    @Json(name = "autoBankPostCode")
    var autoBankPostCode: Any? = null,
    @Json(name = "bankAccountVerifiedStatus")
    var bankAccountVerifiedStatus: Int? = null,
    @Json(name = "bankAddress")
    var bankAddress: Any? = null,
    @Json(name = "bankBranch")
    var bankBranch: Any? = null,
    @Json(name = "bankCity")
    var bankCity: Any? = null,
    @Json(name = "bankCode")
    var bankCode: Any? = null,
    @Json(name = "bankCountryId")
    var bankCountryId: Int? = null,
    @Json(name = "bankCountryName")
    var bankCountryName: Any? = null,
    @Json(name = "bankName")
    var bankName: Any? = null,
    @Json(name = "bankPassbookImage")
    var bankPassbookImage: Any? = null,
    @Json(name = "bankTransferMode")
    var bankTransferMode: Int? = null,
    @Json(name = "bicSwiftCode")
    var bicSwiftCode: Any? = null,
    @Json(name = "branchCode")
    var branchCode: Any? = null,
    @Json(name = "bsbAbaRoutingNumber")
    var bsbAbaRoutingNumber: Any? = null,
    @Json(name = "chassisNumber")
    var chassisNumber: String? = null,
    @Json(name = "cityId")
    var cityId: Int? = null,
    @Json(name = "cityName")
    var cityName: String? = null,
    @Json(name = "company")
    var company: Any? = null,
    @Json(name = "contractFileName")
    var contractFileName: Any? = null,
    @Json(name = "contractId")
    var contractId: Int? = null,
    @Json(name = "contractName")
    var contractName: Any? = null,
    @Json(name = "countryId")
    var countryId: Int? = null,
    @Json(name = "countryName")
    var countryName: String? = null,
    @Json(name = "createdBy")
    var createdBy: String? = null,
    @Json(name = "createdDate")
    var createdDate: String? = null,
    @Json(name = "csmUserid")
    var csmUserid: Int? = null,
    @Json(name = "currency")
    var currency: Any? = null,
    @Json(name = "currencyId")
    var currencyId: Int? = null,
    @Json(name = "custFamilyId")
    var custFamilyId: Int? = null,
    @Json(name = "customerCategory")
    var customerCategory: Any? = null,
    @Json(name = "customerCategoryId")
    var customerCategoryId: Int? = null,
    @Json(name = "customerDetailId")
    var customerDetailId: Int? = null,
    @Json(name = "customerGrade")
    var customerGrade: String? = null,
    @Json(name = "customer_Grade_ID")
    var customerGradeID: Int? = null,
    @Json(name = "customerId")
    var customerId: Int? = null,
    @Json(name = "customerOrderCount")
    var customerOrderCount: Int? = null,
    @Json(name = "customerRelationshipId")
    var customerRelationshipId: Int? = null,
    @Json(name = "customerRemarks")
    var customerRemarks: Any? = null,
    @Json(name = "customerType")
    var customerType: String? = null,
    @Json(name = "customerTypeID")
    var customerTypeID: Int? = null,
    @Json(name = "customerTypeId")
    var customerTypeId: Int? = null,
    @Json(name = "dealerName")
    var dealerName: Any? = null,
    @Json(name = "dealerUserId")
    var dealerUserId: Any? = null,
    @Json(name = "departmentId")
    var departmentId: Int? = null,
    @Json(name = "designationId")
    var designationId: Int? = null,
    @Json(name = "displayImage")
    var displayImage: Any? = null,
    @Json(name = "district")
    var district: String? = null,
    @Json(name = "districtId")
    var districtId: Int? = null,
    @Json(name = "districtName")
    var districtName: Any? = null,
    @Json(name = "dob")
    var dob: Any? = null,
    @Json(name = "domain")
    var domain: Any? = null,
    @Json(name = "email")
    var email: String? = null,
    @Json(name = "emailStatus")
    var emailStatus: Int? = null,
    @Json(name = "engineNumber")
    var engineNumber: Any? = null,
    @Json(name = "enrollmentReferenceDate")
    var enrollmentReferenceDate: Any? = null,
    @Json(name = "enrollmentReferenceNumber")
    var enrollmentReferenceNumber: String? = null,
    @Json(name = "enrollmentStatus")
    var enrollmentStatus: Boolean? = null,
    @Json(name = "ewarrentReg")
    var ewarrentReg: Any? = null,
    @Json(name = "executiveName")
    var executiveName: Any? = null,
    @Json(name = "familyMemberBirthday")
    var familyMemberBirthday: Any? = null,
    @Json(name = "familyMemberName")
    var familyMemberName: Any? = null,
    @Json(name = "firmName")
    var firmName: Any? = null,
    @Json(name = "firstName")
    var firstName: String? = null,
    @Json(name = "gender")
    var gender: Any? = null,
    @Json(name = "ibanNumber")
    var ibanNumber: Any? = null,
    @Json(name = "identificationNo")
    var identificationNo: Any? = null,
    @Json(name = "identificationOthers")
    var identificationOthers: Any? = null,
    @Json(name = "ifscCode")
    var ifscCode: Any? = null,
    @Json(name = "incomeRangeId")
    var incomeRangeId: Int? = null,
    @Json(name = "insuranceExpDate")
    var insuranceExpDate: Any? = null,
    @Json(name = "insuranceRenewalAmount")
    var insuranceRenewalAmount: Int? = null,
    @Json(name = "invoiceAmount")
    var invoiceAmount: Any? = null,
    @Json(name = "invoiceDate")
    var invoiceDate: String? = null,
    @Json(name = "invoiceImage")
    var invoiceImage: Any? = null,
    @Json(name = "invoiceNo")
    var invoiceNo: Any? = null,
    @Json(name = "invoiceNumber")
    var invoiceNumber: Any? = null,
    @Json(name = "isActive")
    var isActive: Int? = null,
    @Json(name = "isBankPassbookNewImage")
    var isBankPassbookNewImage: Boolean? = null,
    @Json(name = "isBlackListed")
    var isBlackListed: Boolean? = null,
    @Json(name = "isDelete")
    var isDelete: Int? = null,
    @Json(name = "isGradeVerified")
    var isGradeVerified: Boolean? = null,
    @Json(name = "isSmartphone")
    var isSmartphone: Int? = null,
    @Json(name = "isSmartphoneUser")
    var isSmartphoneUser: Boolean? = null,
    @Json(name = "isUPIVerified")
    var isUPIVerified: Int? = null,
    @Json(name = "isUpdatePassword")
    var isUpdatePassword: Boolean? = null,
    @Json(name = "isVerified")
    var isVerified: Int? = null,
    @Json(name = "isVinChassis_Active")
    var isVinChassisActive: Any? = null,
    @Json(name = "isWhatsapp")
    var isWhatsapp: Int? = null,
    @Json(name = "isWhatsappUser")
    var isWhatsappUser: Boolean? = null,
    @Json(name = "jAnniversary")
    var jAnniversary: Any? = null,
    @Json(name = "jCreatedDate")
    var jCreatedDate: Any? = null,
    @Json(name = "jD_InvoiceDate")
    var jDInvoiceDate: Any? = null,
    @Json(name = "jD_InvoiceNo")
    var jDInvoiceNo: Any? = null,
    @Json(name = "jDateOfSale")
    var jDateOfSale: Any? = null,
    @Json(name = "jEnrollmentReferenceDate")
    var jEnrollmentReferenceDate: Any? = null,
    @Json(name = "jInsuranceExpDate")
    var jInsuranceExpDate: Any? = null,
    @Json(name = "jPolicyDate")
    var jPolicyDate: Any? = null,
    @Json(name = "jdob")
    var jdob: Any? = null,
    @Json(name = "jjD_InvoiceDate")
    var jjDInvoiceDate: Any? = null,
    @Json(name = "lIdentificationType")
    var lIdentificationType: Int? = null,
    @Json(name = "laborAmount")
    var laborAmount: Int? = null,
    @Json(name = "landmark")
    var landmark: String? = null,
    @Json(name = "languageId")
    var languageId: Int? = null,
    @Json(name = "languageName")
    var languageName: Any? = null,
    @Json(name = "lastName")
    var lastName: String? = null,
    @Json(name = "locality")
    var locality: String? = null,
    @Json(name = "locationCode")
    var locationCode: Any? = null,
    @Json(name = "locationId")
    var locationId: Int? = null,
    @Json(name = "locationName")
    var locationName: String? = null,
    @Json(name = "loyaltyId")
    var loyaltyId: String? = null,
    @Json(name = "loyaltyIdAutoGen")
    var loyaltyIdAutoGen: Boolean? = null,
    @Json(name = "mappedDealerID")
    var mappedDealerID: Int? = null,
    @Json(name = "maritalStatus")
    var maritalStatus: Any? = null,
    @Json(name = "memberName")
    var memberName: Any? = null,
    @Json(name = "memberSince")
    var memberSince: Any? = null,
    @Json(name = "merchantId")
    var merchantId: Int? = null,
    @Json(name = "mobile")
    var mobile: String? = null,
    @Json(name = "mobileNumberLimitation")
    var mobileNumberLimitation: Int? = null,
    @Json(name = "mobilePrefix")
    var mobilePrefix: String? = null,
    @Json(name = "mobile_Two")
    var mobileTwo: String? = null,
    @Json(name = "modelNumber")
    var modelNumber: String? = null,
    @Json(name = "nativeCountryId")
    var nativeCountryId: Int? = null,
    @Json(name = "nativeStateId")
    var nativeStateId: Int? = null,
    @Json(name = "nativeStateName")
    var nativeStateName: Any? = null,
    @Json(name = "nominee")
    var nominee: Any? = null,
    @Json(name = "nomineeDOB")
    var nomineeDOB: Any? = null,
    @Json(name = "parentCustomerId")
    var parentCustomerId: Int? = null,
    @Json(name = "password")
    var password: Any? = null,
    @Json(name = "payOut")
    var payOut: Int? = null,
    @Json(name = "plainPassword")
    var plainPassword: Any? = null,
    @Json(name = "plumberMap")
    var plumberMap: Any? = null,
    @Json(name = "pointBalance")
    var pointBalance: Double? = null,
    @Json(name = "policyDate")
    var policyDate: Any? = null,
    @Json(name = "policyNumber")
    var policyNumber: String? = null,
    @Json(name = "preferedDealerName")
    var preferedDealerName: Any? = null,
    @Json(name = "professionId")
    var professionId: Int? = null,
    @Json(name = "profilePicture")
    var profilePicture: Any? = null,
    @Json(name = "recipientPhonenumber")
    var recipientPhonenumber: Any? = null,
    @Json(name = "recipientType")
    var recipientType: Any? = null,
    @Json(name = "referedBy")
    var referedBy: Any? = null,
    @Json(name = "referralCode")
    var referralCode: Any? = null,
    @Json(name = "referrerCode")
    var referrerCode: Any? = null,
    @Json(name = "regStatus")
    var regStatus: Int? = null,
    @Json(name = "regType")
    var regType: String? = null,
    @Json(name = "registrationSource")
    var registrationSource: Int? = null,
    @Json(name = "relateD_PROJECT_TYPE")
    var relateDPROJECTTYPE: Any? = null,
    @Json(name = "relationship")
    var relationship: Any? = null,
    @Json(name = "religionID")
    var religionID: Int? = null,
    @Json(name = "remarks")
    var remarks: Any? = null,
    @Json(name = "smartPhoneUser")
    var smartPhoneUser: Any? = null,
    @Json(name = "ssid")
    var ssid: Any? = null,
    @Json(name = "stateId")
    var stateId: Int? = null,
    @Json(name = "stateName")
    var stateName: String? = null,
    @Json(name = "talukId")
    var talukId: Int? = null,
    @Json(name = "talukName")
    var talukName: Any? = null,
    @Json(name = "taxId")
    var taxId: Any? = null,
    @Json(name = "tehsilBlockMandal")
    var tehsilBlockMandal: String? = null,
    @Json(name = "territoryId")
    var territoryId: Int? = null,
    @Json(name = "title")
    var title: String? = null,
    @Json(name = "tradeLicence")
    var tradeLicence: Any? = null,
    @Json(name = "upI_ID")
    var upIID: Any? = null,
    @Json(name = "upiAttachment")
    var upiAttachment: Any? = null,
    @Json(name = "upiName")
    var upiName: Any? = null,
    @Json(name = "user")
    var user: Any? = null,
    @Json(name = "userId")
    var userId: Int? = null,
    @Json(name = "vehicleBrand")
    var vehicleBrand: Any? = null,
    @Json(name = "vehicleID")
    var vehicleID: Int? = null,
    @Json(name = "vehicleNumber")
    var vehicleNumber: String? = null,
    @Json(name = "vehicleType")
    var vehicleType: Any? = null,
    @Json(name = "verifiedStatus")
    var verifiedStatus: Any? = null,
    @Json(name = "village")
    var village: String? = null,
    @Json(name = "walletNumber")
    var walletNumber: Any? = null,
    @Json(name = "walletVerifiedStatus")
    var walletVerifiedStatus: Boolean? = null,
    @Json(name = "whatsAPPUser")
    var whatsAPPUser: Any? = null,
    @Json(name = "whatsAppNumber")
    var whatsAppNumber: Any? = null,
    @Json(name = "zip")
    var zip: String? = null
)

@JsonClass(generateAdapter = true)
data class ObjCustomerDetailssss(
    @Json(name = "absent_Count")
    var absentCount: Int? = null,
    @Json(name = "address")
    var address: Any? = null,
    @Json(name = "ageGroupId")
    var ageGroupId: Int? = null,
    @Json(name = "anniversary")
    var anniversary: Any? = null,
    @Json(name = "attendanceDate")
    var attendanceDate: Any? = null,
    @Json(name = "bonusDate")
    var bonusDate: Any? = null,
    @Json(name = "bonusName")
    var bonusName: Any? = null,
    @Json(name = "bonusValue")
    var bonusValue: Any? = null,
    @Json(name = "callRemarks")
    var callRemarks: Any? = null,
    @Json(name = "callStatusId")
    var callStatusId: Int? = null,
    @Json(name = "cashBack")
    var cashBack: Int? = null,
    @Json(name = "company")
    var company: Any? = null,
    @Json(name = "customerDetailId")
    var customerDetailId: Int? = null,
    @Json(name = "customerGrade")
    var customerGrade: Any? = null,
    @Json(name = "customerId")
    var customerId: Int? = null,
    @Json(name = "customerRemarks")
    var customerRemarks: Any? = null,
    @Json(name = "designation")
    var designation: Any? = null,
    @Json(name = "district")
    var district: Any? = null,
    @Json(name = "districtId")
    var districtId: Int? = null,
    @Json(name = "emailStatus")
    var emailStatus: Int? = null,
    @Json(name = "encashBalance")
    var encashBalance: Int? = null,
    @Json(name = "executiveName")
    var executiveName: Any? = null,
    @Json(name = "firstName")
    var firstName: Any? = null,
    @Json(name = "gender")
    var gender: Any? = null,
    @Json(name = "identificationNo")
    var identificationNo: Any? = null,
    @Json(name = "identificationOthers")
    var identificationOthers: Any? = null,
    @Json(name = "incomeRangeId")
    var incomeRangeId: Int? = null,
    @Json(name = "isBlacklisted")
    var isBlacklisted: Int? = null,
    @Json(name = "isDealerMapped")
    var isDealerMapped: Int? = null,
    @Json(name = "isDormant")
    var isDormant: Int? = null,
    @Json(name = "isGradeVerified")
    var isGradeVerified: Boolean? = null,
    @Json(name = "isNewProfilePicture")
    var isNewProfilePicture: Boolean? = null,
    @Json(name = "isOnHold")
    var isOnHold: Int? = null,
    @Json(name = "isSmartphoneUser")
    var isSmartphoneUser: Boolean? = null,
    @Json(name = "isWhatsappUser")
    var isWhatsappUser: Boolean? = null,
    @Json(name = "issueDescription")
    var issueDescription: Any? = null,
    @Json(name = "jAnniversary")
    var jAnniversary: Any? = null,
    @Json(name = "lIdentificationType")
    var lIdentificationType: Int? = null,
    @Json(name = "languageID")
    var languageID: Int? = null,
    @Json(name = "languageId")
    var languageId: Int? = null,
    @Json(name = "languageName")
    var languageName: Any? = null,
    @Json(name = "lastName")
    var lastName: Any? = null,
    @Json(name = "locationId")
    var locationId: Int? = null,
    @Json(name = "locationName")
    var locationName: Any? = null,
    @Json(name = "loyaltyId")
    var loyaltyId: Any? = null,
    @Json(name = "maritalStatus")
    var maritalStatus: Any? = null,
    @Json(name = "month_Name")
    var monthName: Any? = null,
    @Json(name = "month_No")
    var monthNo: Int? = null,
    @Json(name = "nativeStateId")
    var nativeStateId: Int? = null,
    @Json(name = "nativeStateName")
    var nativeStateName: Any? = null,
    @Json(name = "ownerName")
    var ownerName: Any? = null,
    @Json(name = "pinStatus")
    var pinStatus: Int? = null,
    @Json(name = "present")
    var present: Boolean? = null,
    @Json(name = "present_Count")
    var presentCount: Int? = null,
    @Json(name = "professionId")
    var professionId: Int? = null,
    @Json(name = "profilePicture")
    var profilePicture: Any? = null,
    @Json(name = "qrCode")
    var qrCode: Any? = null,
    @Json(name = "religionID")
    var religionID: Int? = null,
    @Json(name = "requiredPoints")
    var requiredPoints: Int? = null,
    @Json(name = "storeName")
    var storeName: Any? = null,
    @Json(name = "talukId")
    var talukId: Int? = null,
    @Json(name = "tardy")
    var tardy: Boolean? = null,
    @Json(name = "tardy_Count")
    var tardyCount: Int? = null,
    @Json(name = "title")
    var title: Any? = null,
    @Json(name = "type")
    var type: Any? = null,
    @Json(name = "userId")
    var userId: Int? = null,
    @Json(name = "verificationStatus")
    var verificationStatus: Any? = null,
    @Json(name = "verifiedStatus")
    var verifiedStatus: Int? = null,
    @Json(name = "walletNumber")
    var walletNumber: Any? = null
)

@JsonClass(generateAdapter = true)
data class ObjCustomerOfficalInfooo(
    @Json(name = "address")
    var address: Any? = null,
    @Json(name = "bankTransferMode")
    var bankTransferMode: Any? = null,
    @Json(name = "cityId")
    var cityId: Int? = null,
    @Json(name = "cityName")
    var cityName: Any? = null,
    @Json(name = "companyName")
    var companyName: Any? = null,
    @Json(name = "countryId")
    var countryId: Int? = null,
    @Json(name = "countryName")
    var countryName: Any? = null,
    @Json(name = "departmentIdOfficial")
    var departmentIdOfficial: Int? = null,
    @Json(name = "designation")
    var designation: Any? = null,
    @Json(name = "designationIdOfficial")
    var designationIdOfficial: Int? = null,
    @Json(name = "districtId")
    var districtId: Int? = null,
    @Json(name = "establishDate")
    var establishDate: Any? = null,
    @Json(name = "firmAddress")
    var firmAddress: Any? = null,
    @Json(name = "firmMobile")
    var firmMobile: Any? = null,
    @Json(name = "firmSize")
    var firmSize: Any? = null,
    @Json(name = "firmTypeID")
    var firmTypeID: Int? = null,
    @Json(name = "firmTypeName")
    var firmTypeName: Any? = null,
    @Json(name = "gstDocument")
    var gstDocument: Any? = null,
    @Json(name = "gstNumber")
    var gstNumber: Any? = null,
    @Json(name = "incorporationDate")
    var incorporationDate: Any? = null,
    @Json(name = "industryID")
    var industryID: Int? = null,
    @Json(name = "isGSTNumber")
    var isGSTNumber: Any? = null,
    @Json(name = "jobTypeID")
    var jobTypeID: Int? = null,
    @Json(name = "jobTypeName")
    var jobTypeName: Any? = null,
    @Json(name = "officalEmail")
    var officalEmail: Any? = null,
    @Json(name = "ownerName")
    var ownerName: Any? = null,
    @Json(name = "phoneOffice")
    var phoneOffice: Any? = null,
    @Json(name = "phoneResidence")
    var phoneResidence: Any? = null,
    @Json(name = "sapCode")
    var sapCode: Any? = null,
    @Json(name = "stateId")
    var stateId: Int? = null,
    @Json(name = "stateName")
    var stateName: Any? = null,
    @Json(name = "stdCode")
    var stdCode: Any? = null,
    @Json(name = "storeName")
    var storeName: Any? = null,
    @Json(name = "tahasilImage")
    var tahasilImage: Any? = null,
    @Json(name = "talukId")
    var talukId: Int? = null,
    @Json(name = "targetCreditPeriod")
    var targetCreditPeriod: Int? = null,
    @Json(name = "targetPoint")
    var targetPoint: Int? = null,
    @Json(name = "targetValue")
    var targetValue: Int? = null,
    @Json(name = "venderCode")
    var venderCode: Any? = null,
    @Json(name = "zip")
    var zip: Any? = null
)







/*@JsonClass(generateAdapter = true)
data class GetCustomerDetailsResponse(
    @Json(name = "audienceOptimizationId") 
    val audienceOptimizationId: Any? = null,
    @Json(name = "bindYearWiseAttendanceList") 
    val bindYearWiseAttendanceList: Any? = null,
    @Json(name = "customerBasicInfoList") 
    val customerBasicInfoList: List<Any>? = null,
    @Json(name = "customerFamilyList") 
    val customerFamilyList: List<Any>? = null,
    @Json(name = "customerMappingList") 
    val customerMappingList: Any? = null,
    @Json(name = "customerOptimizationDetailsList") 
    val customerOptimizationDetailsList: Any? = null,
    @Json(name = "customerPreferenceList") 
    val customerPreferenceList: List<Any>? = null,
    @Json(name = "distributorlst") 
    val distributorlst: Any? = null,
    @Json(name = "expiredReferalCount") 
    val expiredReferalCount: Int? = null,
    @Json(name = "hierarchyMapDetails") 
    val hierarchyMapDetails: HierarchyMapDetails? = null,
    @Json(name = "hierarchyMapDetailsList") 
    val hierarchyMapDetailsList: Any? = null,
    @Json(name = "lstCustomer") 
    val lstCustomer: Any? = null,
    @Json(name = "lstCustomerEntityMapping") 
    val lstCustomerEntityMapping: Any? = null,
    @Json(name = "lstCustomerIdentityInfo") 
    val lstCustomerIdentityInfo: List<LstCustomerIdentityInfo>? = null,
    @Json(name = "lstCustomerOfficalInfo") 
    val lstCustomerOfficalInfo: Any? = null,
    @Json(name = "lstCustomerPaymentModeDetails") 
    val lstCustomerPaymentModeDetails: Any? = null,
    @Json(name = "lstCustomerRemarksHistory") 
    val lstCustomerRemarksHistory: Any? = null,
    @Json(name = "lstCustomerSearchDetails") 
    val lstCustomerSearchDetails: Any? = null,
    @Json(name = "lstRewardTransDetails") 
    val lstRewardTransDetails: Any? = null,
    @Json(name = "lstRewardTransactionBasedonProduct") 
    val lstRewardTransactionBasedonProduct: Any? = null,
    @Json(name = "lstSchemeConfigureationDetails") 
    val lstSchemeConfigureationDetails: Any? = null,
    @Json(name = "lstVehicleDetails") 
    val lstVehicleDetails: Any? = null,
    @Json(name = "lstWorkSiteInfoDetails") 
    val lstWorkSiteInfoDetails: Any? = null,
    @Json(name = "mappedCustomersList") 
    val mappedCustomersList: Any? = null,
    @Json(name = "mappedProductList") 
    val mappedProductList: List<Any>? = null,
    @Json(name = "objCustomer") 
    val objCustomer: ObjCustomerrr? = null,
    @Json(name = "objCustomerDetails") 
    val objCustomerDetails: ObjCustomerDetailssss? = null,
  @Json(name = "objCustomerOfficalInfo")
      val objCustomerOfficalInfo: ObjCustomerOfficalInfooo? = null,

    @Json(name = "pendingReferalCount") 
    val pendingReferalCount: Int? = null,
    @Json(name = "pointBal") 
    val pointBal: Any? = null,
    @Json(name = "retailerlst") 
    val retailerlst: Any? = null,
    @Json(name = "returnMessage") 
    val returnMessage: Any? = null,
    @Json(name = "returnValue") 
    val returnValue: Int? = null,
    @Json(name = "subscriptionDetails") 
    val subscriptionDetails: Any? = null,
    @Json(name = "succcessReferealCount") 
    val succcessReferealCount: Int? = null,
    @Json(name = "totEarned") 
    val totEarned: Any? = null,
    @Json(name = "totPointExpired") 
    val totPointExpired: Any? = null,
    @Json(name = "totRedeem") 
    val totRedeem: Any? = null,
    @Json(name = "totSalesReturn") 
    val totSalesReturn: Any? = null,
    @Json(name = "totalRecords") 
    val totalRecords: Int? = null,
    @Json(name = "totalWithDrawls") 
    val totalWithDrawls: Int? = null
)

@JsonClass(generateAdapter = true)
data class HierarchyMapDetails(
    @Json(name = "asmName") 
    val asmName: Any? = null,
    @Json(name = "customerType") 
    val customerType: Any? = null,
    @Json(name = "customerUserID") 
    val customerUserID: Int? = null,
    @Json(name = "customerUserName") 
    val customerUserName: Any? = null,
    @Json(name = "hieracMasterMapID") 
    val hieracMasterMapID: Int? = null,
    @Json(name = "locationID") 
    val locationID: Int? = null,
    @Json(name = "locationName") 
    val locationName: Any? = null,
    @Json(name = "parentUserID") 
    val parentUserID: Int? = null,
    @Json(name = "seMobileNo") 
    val seMobileNo: Any? = null,
    @Json(name = "seName") 
    val seName: Any? = null,
    @Json(name = "user2UserID") 
    val user2UserID: Int? = null,
    @Json(name = "userUserID") 
    val userUserID: Int? = null,
    @Json(name = "userUseruName") 
    val userUseruName: Any? = null
)

@JsonClass(generateAdapter = true)
data class LstCustomerIdentityInfo(
    @Json(name = "identityDocument") 
    var identityDocument: String? = null,
    @Json(name = "identityID") 
    var identityID: Int? = null,
    @Json(name = "identityName") 
    var identityName: String? = null,
    @Json(name = "identityNo") 
    var identityNo: String? = null,
    @Json(name = "identityType") 
    var identityType: String? = null,
    @Json(name = "identityTypeID") 
    var identityTypeID: Int? = null,
    @Json(name = "isNewIdentity") 
    var isNewIdentity: Boolean? = null
) : Serializable

@JsonClass(generateAdapter = true)
data class ObjCustomerrr(
    @Json(name = "accountComStatus") 
    val accountComStatus: Int? = null,
    @Json(name = "accountNumber") 
    val accountNumber: Any? = null,
    @Json(name = "accountStatus") 
    val accountStatus: Any? = null,
    @Json(name = "accountStatusId") 
    val accountStatusId: Int? = null,
    @Json(name = "accountType") 
    val accountType: Any? = null,
    @Json(name = "accountTypeId") 
    val accountTypeId: Int? = null,
    @Json(name = "acountHolderName") 
    val acountHolderName: Any? = null,
    @Json(name = "actionType") 
    val actionType: Int? = null,
    @Json(name = "actorId") 
    val actorId: Int? = null,
    @Json(name = "actorRole") 
    val actorRole: Any? = null,
    @Json(name = "address") 
    val address: Any? = null,
    @Json(name = "address1") 
    val address1: String? = null,
    @Json(name = "address2") 
    val address2: String? = null,
    @Json(name = "addressId") 
    val addressId: Int? = null,
    @Json(name = "addressLatitude") 
    val addressLatitude: Any? = null,
    @Json(name = "addressLongitude") 
    val addressLongitude: Any? = null,
    @Json(name = "anniversary") 
    val anniversary: String? = null,
    @Json(name = "areaId") 
    val areaId: Int? = null,
    @Json(name = "areaName") 
    val areaName: Any? = null,
    @Json(name = "autoAccountType") 
    val autoAccountType: Any? = null,
    @Json(name = "autoBankCounty") 
    val autoBankCounty: Any? = null,
    @Json(name = "avgRunningPerMonth") 
    val avgRunningPerMonth: Double? = null,
    @Json(name = "bankAccountVerifiedStatus") 
    val bankAccountVerifiedStatus: Int? = null,
    @Json(name = "bankAddress") 
    val bankAddress: Any? = null,
    @Json(name = "bankBranch") 
    val bankBranch: Any? = null,
    @Json(name = "bankCity") 
    val bankCity: Any? = null,
    @Json(name = "bankCode") 
    val bankCode: Any? = null,
    @Json(name = "bankCountryID") 
    val bankCountryID: Int? = null,
    @Json(name = "bankCurrencyID") 
    val bankCurrencyID: Int? = null,
    @Json(name = "bankIbanNumber") 
    val bankIbanNumber: Any? = null,
    @Json(name = "bankName") 
    val bankName: Any? = null,
    @Json(name = "bankPassbookImage") 
    val bankPassbookImage: Any? = null,
    @Json(name = "bankPostCode") 
    val bankPostCode: Any? = null,
    @Json(name = "bankRoutingNumber") 
    val bankRoutingNumber: Any? = null,
    @Json(name = "bankSwiftCode") 
    val bankSwiftCode: Any? = null,
    @Json(name = "book_App_Date") 
    val bookAppDate: String? = null,
    @Json(name = "branchCode") 
    val branchCode: Any? = null,
    @Json(name = "chassisNumber") 
    val chassisNumber: String? = null,
    @Json(name = "cityId") 
    val cityId: Int? = null,
    @Json(name = "cityName") 
    val cityName: Any? = null,
    @Json(name = "company") 
    val company: Any? = null,
    @Json(name = "contactID") 
    val contactID: Int? = null,
    @Json(name = "contactName") 
    val contactName: Any? = null,
    @Json(name = "contactPhone") 
    val contactPhone: Any? = null,
    @Json(name = "contractFileName") 
    val contractFileName: Any? = null,
    @Json(name = "contractId") 
    val contractId: Int? = null,
    @Json(name = "contractName") 
    val contractName: Any? = null,
    @Json(name = "countryId") 
    val countryId: Int? = null,
    @Json(name = "countryName") 
    val countryName: String? = null,
    @Json(name = "createdBy") 
    val createdBy: String? = null,
    @Json(name = "createdDate") 
    val createdDate: String? = null,
    @Json(name = "currency") 
    val currency: Any? = null,
    @Json(name = "custAccountType") 
    val custAccountType: Any? = null,
    @Json(name = "customerCategory") 
    val customerCategory: Any? = null,
    @Json(name = "customerCategoryId") 
    val customerCategoryId: Int? = null,
    @Json(name = "customerCityId") 
    val customerCityId: Int? = null,
    @Json(name = "customerDob") 
    val customerDob: Any? = null,
    @Json(name = "customerEmail") 
    val customerEmail: String? = null,
    @Json(name = "customerGrade") 
    val customerGrade: String? = null,
    @Json(name = "customer_Grade_ID") 
    val customerGradeID: Int? = null,
    @Json(name = "customerId") 
    val customerId: Int? = null,
    @Json(name = "customerIsActive") 
    val customerIsActive: Boolean? = null,
    @Json(name = "customerMenuId") 
    val customerMenuId: Any? = null,
    @Json(name = "customerMobile") 
    val customerMobile: String? = null,
    @Json(name = "customerOrderCount") 
    val customerOrderCount: Int? = null,
    @Json(name = "customerRelationshipId") 
    val customerRelationshipId: Int? = null,
    @Json(name = "customerRewardCardBalance") 
    val customerRewardCardBalance: Int? = null,
    @Json(name = "customerRewardPoints") 
    val customerRewardPoints: Int? = null,
    @Json(name = "customerStateId") 
    val customerStateId: Int? = null,
    @Json(name = "customerType") 
    val customerType: String? = null,
    @Json(name = "customerTypeID") 
    val customerTypeID: Int? = null,
    @Json(name = "customerTypeId") 
    val customerTypeId: Int? = null,
    @Json(name = "customerZip") 
    val customerZip: String? = null,
    @Json(name = "customersRemarks") 
    val customersRemarks: Any? = null,
    @Json(name = "dateOfSale") 
    val dateOfSale: String? = null,
    @Json(name = "debitedGiftCardAmount") 
    val debitedGiftCardAmount: Double? = null,
    @Json(name = "departmentId") 
    val departmentId: Int? = null,
    @Json(name = "designation") 
    val designation: Any? = null,
    @Json(name = "designationId") 
    val designationId: Int? = null,
    @Json(name = "displayImage") 
    val displayImage: Any? = null,
    @Json(name = "district") 
    val district: String? = null,
    @Json(name = "districtId") 
    val districtId: Int? = null,
    @Json(name = "districtName") 
    val districtName: Any? = null,
    @Json(name = "dob") 
    val dob: String? = null,
    @Json(name = "domain") 
    val domain: Any? = null,
    @Json(name = "drivenBy") 
    val drivenBy: Any? = null,
    @Json(name = "email") 
    val email: Any? = null,
    @Json(name = "encashBalance") 
    val encashBalance: Int? = null,
    @Json(name = "engineNumber") 
    val engineNumber: Any? = null,
    @Json(name = "enrolledBy") 
    val enrolledBy: Any? = null,
    @Json(name = "enrollmentBonus") 
    val enrollmentBonus: Int? = null,
    @Json(name = "enrollmentId") 
    val enrollmentId: Any? = null,
    @Json(name = "enrollmentReferenceDate") 
    val enrollmentReferenceDate: String? = null,
    @Json(name = "enrollmentReferenceNumber") 
    val enrollmentReferenceNumber: String? = null,
    @Json(name = "enrollmentStatus") 
    val enrollmentStatus: Boolean? = null,
    @Json(name = "financeEmailId") 
    val financeEmailId: Any? = null,
    @Json(name = "financeName") 
    val financeName: Any? = null,
    @Json(name = "financeUserName") 
    val financeUserName: Any? = null,
    @Json(name = "financialDate") 
    val financialDate: Any? = null,
    @Json(name = "firstName") 
    val firstName: String? = null,
    @Json(name = "fromDate") 
    val fromDate: String? = null,
    @Json(name = "frontofficeExecutive") 
    val frontofficeExecutive: Any? = null,
    @Json(name = "gender") 
    val gender: Any? = null,
    @Json(name = "giftCardAmount") 
    val giftCardAmount: Double? = null,
    @Json(name = "giftedGiftCardAmount") 
    val giftedGiftCardAmount: Double? = null,
    @Json(name = "giftedPoints") 
    val giftedPoints: Int? = null,
    @Json(name = "gstNumber") 
    val gstNumber: Any? = null,
    @Json(name = "identificationNo") 
    val identificationNo: Any? = null,
    @Json(name = "identificationTypeID") 
    val identificationTypeID: Int? = null,
    @Json(name = "ifscCode") 
    val ifscCode: Any? = null,
    @Json(name = "image") 
    val image: Any? = null,
    @Json(name = "incorporationDate") 
    val incorporationDate: String? = null,
    @Json(name = "industryId") 
    val industryId: Int? = null,
    @Json(name = "insuranceExpDate") 
    val insuranceExpDate: String? = null,
    @Json(name = "insuranceRenewalAmount") 
    val insuranceRenewalAmount: Int? = null,
    @Json(name = "invoiceAmount") 
    val invoiceAmount: Any? = null,
    @Json(name = "invoiceNo") 
    val invoiceNo: Any? = null,
    @Json(name = "isActive") 
    val isActive: Int? = null,
    @Json(name = "isBankPassbookNewImage") 
    val isBankPassbookNewImage: Boolean? = null,
    @Json(name = "isBlackListed") 
    val isBlackListed: Boolean? = null,
    @Json(name = "isCCVerified") 
    val isCCVerified: Boolean? = null,
    @Json(name = "isDriverChanging") 
    val isDriverChanging: Any? = null,
    @Json(name = "isF2FMeeting") 
    val isF2FMeeting: Boolean? = null,
    @Json(name = "isGradeVerified") 
    val isGradeVerified: Boolean? = null,
    @Json(name = "isIDUploaded") 
    val isIDUploaded: Boolean? = null,
    @Json(name = "isNameUpdated") 
    val isNameUpdated: Boolean? = null,
    @Json(name = "isProfilePictureUploaded") 
    val isProfilePictureUploaded: Boolean? = null,
    @Json(name = "isSemiUpdated") 
    val isSemiUpdated: Boolean? = null,
    @Json(name = "isSiteVerified") 
    val isSiteVerified: Boolean? = null,
    @Json(name = "isUpdatePassword") 
    val isUpdatePassword: Boolean? = null,
    @Json(name = "isVerified") 
    val isVerified: Int? = null,
    @Json(name = "isVinChassis_Active") 
    val isVinChassisActive: Any? = null,
    @Json(name = "issuedGiftCardAmount") 
    val issuedGiftCardAmount: Double? = null,
    @Json(name = "jAnniversary") 
    val jAnniversary: Any? = null,
    @Json(name = "jBook_App_Date") 
    val jBookAppDate: Any? = null,
    @Json(name = "jCreatedDate") 
    val jCreatedDate: Any? = null,
    @Json(name = "jD_InvoiceDate") 
    val jDInvoiceDate: String? = null,
    @Json(name = "jD_InvoiceNo") 
    val jDInvoiceNo: Any? = null,
    @Json(name = "jDateOfSale") 
    val jDateOfSale: Any? = null,
    @Json(name = "jEnrollmentReferenceDate") 
    val jEnrollmentReferenceDate: Any? = null,
    @Json(name = "jInsuranceExpDate") 
    val jInsuranceExpDate: Any? = null,
    @Json(name = "jNomineeDOB") 
    val jNomineeDOB: Any? = null,
    @Json(name = "jPolicyDate") 
    val jPolicyDate: Any? = null,
    @Json(name = "jdob") 
    val jdob: Any? = null,
    @Json(name = "jjD_InvoiceDate") 
    val jjDInvoiceDate: Any? = null,
    @Json(name = "laborAmount") 
    val laborAmount: Int? = null,
    @Json(name = "landlineNumber") 
    val landlineNumber: Any? = null,
    @Json(name = "landmark") 
    val landmark: String? = null,
    @Json(name = "language") 
    val language: Any? = null,
    @Json(name = "languageId") 
    val languageId: Int? = null,
    @Json(name = "lastActive") 
    val lastActive: Any? = null,
    @Json(name = "lastName") 
    val lastName: String? = null,
    @Json(name = "locality") 
    val locality: String? = null,
    @Json(name = "locationCode") 
    val locationCode: Any? = null,
    @Json(name = "locationId") 
    val locationId: Int? = null,
    @Json(name = "locationName") 
    val locationName: String? = null,
    @Json(name = "loyaltyId") 
    val loyaltyId: String? = null,
    @Json(name = "loyaltyIdAutoGen") 
    val loyaltyIdAutoGen: Boolean? = null,
    @Json(name = "memberSince") 
    val memberSince: Any? = null,
    @Json(name = "merchantId") 
    val merchantId: Int? = null,
    @Json(name = "merchantName") 
    val merchantName: Any? = null,
    @Json(name = "mobile") 
    val mobile: Any? = null,
    @Json(name = "mobileNumberLimitation") 
    val mobileNumberLimitation: Int? = null,
    @Json(name = "mobilePrefix") 
    val mobilePrefix: String? = null,
    @Json(name = "mobile_Two") 
    val mobileTwo: String? = null,
    @Json(name = "modelNumber") 
    val modelNumber: String? = null,
    @Json(name = "nativeCountryId") 
    val nativeCountryId: Int? = null,
    @Json(name = "nativeStateId") 
    val nativeStateId: Int? = null,
    @Json(name = "nfcTagID") 
    val nfcTagID: Any? = null,
    @Json(name = "nominee") 
    val nominee: Any? = null,
    @Json(name = "nomineeDOB") 
    val nomineeDOB: String? = null,
    @Json(name = "panStatus") 
    val panStatus: Any? = null,
    @Json(name = "panStatusId") 
    val panStatusId: Int? = null,
    @Json(name = "parentCustomerId") 
    val parentCustomerId: Int? = null,
    @Json(name = "password") 
    val password: Any? = null,
    @Json(name = "payOut") 
    val payOut: Int? = null,
    @Json(name = "payload") 
    val payload: Any? = null,
    @Json(name = "pointBalance") 
    val pointBalance: Int? = null,
    @Json(name = "pointExpired") 
    val pointExpired: Int? = null,
    @Json(name = "policyDate") 
    val policyDate: String? = null,
    @Json(name = "policyNumber") 
    val policyNumber: String? = null,
    @Json(name = "postInternalNote") 
    val postInternalNote: Any? = null,
    @Json(name = "presentKM") 
    val presentKM: Double? = null,
    @Json(name = "profilePicture") 
    val profilePicture: Any? = null,
    @Json(name = "pushId") 
    val pushId: Any? = null,
    @Json(name = "recipientPhonenumber") 
    val recipientPhonenumber: Any? = null,
    @Json(name = "recipientType") 
    val recipientType: Any? = null,
    @Json(name = "referedBy") 
    val referedBy: Any? = null,
    @Json(name = "referralCode") 
    val referralCode: Any? = null,
    @Json(name = "referrerCode") 
    val referrerCode: Any? = null,
    @Json(name = "refundGiftCardAmount") 
    val refundGiftCardAmount: Double? = null,
    @Json(name = "regStatus") 
    val regStatus: Int? = null,
    @Json(name = "regStatusId") 
    val regStatusId: Int? = null,
    @Json(name = "regType") 
    val regType: String? = null,
    @Json(name = "registrationSource") 
    val registrationSource: Int? = null,
    @Json(name = "relateD_PROJECT_TYPE") 
    val relateDPROJECTTYPE: Any? = null,
    @Json(name = "relationship") 
    val relationship: Any? = null,
    @Json(name = "remarks") 
    val remarks: Any? = null,
    @Json(name = "rewardPoint") 
    val rewardPoint: Double? = null,
    @Json(name = "rewardPoints") 
    val rewardPoints: Int? = null,
    @Json(name = "roleID") 
    val roleID: Int? = null,
    @Json(name = "sapNo") 
    val sapNo: Any? = null,
    @Json(name = "searchText") 
    val searchText: Any? = null,
    @Json(name = "sourceOfLogin") 
    val sourceOfLogin: Any? = null,
    @Json(name = "spouseDOB") 
    val spouseDOB: String? = null,
    @Json(name = "spouseName") 
    val spouseName: Any? = null,
    @Json(name = "sscEmailId") 
    val sscEmailId: Any? = null,
    @Json(name = "sscName") 
    val sscName: Any? = null,
    @Json(name = "sscUserName") 
    val sscUserName: Any? = null,
    @Json(name = "stateId") 
    val stateId: Int? = null,
    @Json(name = "stateName") 
    val stateName: Any? = null,
    @Json(name = "subscriptionDurationID") 
    val subscriptionDurationID: Int? = null,
    @Json(name = "talukId") 
    val talukId: Int? = null,
    @Json(name = "talukName") 
    val talukName: Any? = null,
    @Json(name = "targetCreditPeriod") 
    val targetCreditPeriod: Int? = null,
    @Json(name = "targetValue") 
    val targetValue: Int? = null,
    @Json(name = "taxId") 
    val taxId: Any? = null,
    @Json(name = "tehsilBlockMandal") 
    val tehsilBlockMandal: String? = null,
    @Json(name = "title") 
    val title: String? = null,
    @Json(name = "toDate") 
    val toDate: String? = null,
    @Json(name = "token") 
    val token: Any? = null,
    @Json(name = "totalCollection") 
    val totalCollection: Int? = null,
    @Json(name = "totalNetValue") 
    val totalNetValue: Int? = null,
    @Json(name = "tradeLicence") 
    val tradeLicence: Any? = null,
    @Json(name = "userId") 
    val userId: Int? = null,
    @Json(name = "userName") 
    val userName: Any? = null,
    @Json(name = "vehicleID") 
    val vehicleID: Int? = null,
    @Json(name = "vehicleNumber") 
    val vehicleNumber: String? = null,
    @Json(name = "vehicleType") 
    val vehicleType: Any? = null,
    @Json(name = "vendorCode") 
    val vendorCode: Any? = null,
    @Json(name = "verifiedStatus") 
    val verifiedStatus: Any? = null,
    @Json(name = "village") 
    val village: String? = null,
    @Json(name = "walletName") 
    val walletName: Any? = null,
    @Json(name = "walletNumber") 
    val walletNumber: Any? = null,
    @Json(name = "walletVerifiedStatus") 
    val walletVerifiedStatus: Boolean? = null,
    @Json(name = "whatsAppNumber") 
    val whatsAppNumber: Any? = null,
    @Json(name = "zip") 
    val zip: Any? = null
)

@JsonClass(generateAdapter = true)
data class ObjCustomerDetailssss(
    @Json(name = "absent_Count") 
    val absentCount: Int? = null,
    @Json(name = "accountStatusId") 
    val accountStatusId: Int? = null,
    @Json(name = "address") 
    val address: Any? = null,
    @Json(name = "addressProofDocument") 
    val addressProofDocument: Any? = null,
    @Json(name = "addressProofId") 
    val addressProofId: Any? = null,
    @Json(name = "addressProofType") 
    val addressProofType: Any? = null,
    @Json(name = "ageGroupId") 
    val ageGroupId: Int? = null,
    @Json(name = "anniversary") 
    val anniversary: String? = null,
    @Json(name = "attendanceDate") 
    val attendanceDate: String? = null,
    @Json(name = "bonusDate") 
    val bonusDate: Any? = null,
    @Json(name = "bonusName") 
    val bonusName: Any? = null,
    @Json(name = "bonusValue") 
    val bonusValue: Any? = null,
    @Json(name = "callRemarks") 
    val callRemarks: Any? = null,
    @Json(name = "callStatusId") 
    val callStatusId: Int? = null,
    @Json(name = "cashBack") 
    val cashBack: Int? = null,
    @Json(name = "color") 
    val color: Any? = null,
    @Json(name = "company") 
    val company: Any? = null,
    @Json(name = "customerDetailId") 
    val customerDetailId: Int? = null,
    @Json(name = "customerGrade") 
    val customerGrade: Any? = null,
    @Json(name = "customerId") 
    val customerId: Int? = null,
    @Json(name = "customerRemarks") 
    val customerRemarks: Any? = null,
    @Json(name = "designation") 
    val designation: Any? = null,
    @Json(name = "district") 
    val district: Any? = null,
    @Json(name = "districtId") 
    val districtId: Int? = null,
    @Json(name = "emailStatus") 
    val emailStatus: Int? = null,
    @Json(name = "encashBalance") 
    val encashBalance: Int? = null,
    @Json(name = "executiveName") 
    val executiveName: Any? = null,
    @Json(name = "firstName") 
    val firstName: Any? = null,
    @Json(name = "gender") 
    val gender: String? = null,
    @Json(name = "identificationNo") 
    val identificationNo: Any? = null,
    @Json(name = "identificationOthers") 
    val identificationOthers: Any? = null,
    @Json(name = "identityProofDocument") 
    val identityProofDocument: Any? = null,
    @Json(name = "identityProofId") 
    val identityProofId: Any? = null,
    @Json(name = "identityProofType") 
    val identityProofType: Any? = null,
    @Json(name = "incomeRangeId") 
    val incomeRangeId: Int? = null,
    @Json(name = "isBlacklisted") 
    val isBlacklisted: Int? = null,
    @Json(name = "isDealerMapped") 
    val isDealerMapped: Int? = null,
    @Json(name = "isDormant") 
    val isDormant: Int? = null,
    @Json(name = "isGradeVerified") 
    val isGradeVerified: Boolean? = null,
    @Json(name = "isNewProfilePicture") 
    val isNewProfilePicture: Boolean? = null,
    @Json(name = "isOnHold") 
    val isOnHold: Int? = null,
    @Json(name = "isSmartphoneUser") 
    val isSmartphoneUser: Boolean? = null,
    @Json(name = "isWhatsappUser") 
    val isWhatsappUser: Boolean? = null,
    @Json(name = "issueDescription") 
    val issueDescription: Any? = null,
    @Json(name = "jAnniversary") 
    val jAnniversary: Any? = null,
    @Json(name = "lIdentificationType") 
    val lIdentificationType: Int? = null,
    @Json(name = "languageID") 
    val languageID: Int? = null,
    @Json(name = "languageId") 
    val languageId: Int? = null,
    @Json(name = "languageName") 
    val languageName: Any? = null,
    @Json(name = "lastName") 
    val lastName: Any? = null,
    @Json(name = "locationId") 
    val locationId: Int? = null,
    @Json(name = "locationName") 
    val locationName: Any? = null,
    @Json(name = "loyaltyId") 
    val loyaltyId: Any? = null,
    @Json(name = "maritalStatus") 
    val maritalStatus: String? = null,
    @Json(name = "month_Name") 
    val monthName: Any? = null,
    @Json(name = "month_No") 
    val monthNo: Int? = null,
    @Json(name = "nativeStateId") 
    val nativeStateId: Int? = null,
    @Json(name = "nativeStateName") 
    val nativeStateName: Any? = null,
    @Json(name = "ownerName") 
    val ownerName: Any? = null,
    @Json(name = "pinStatus") 
    val pinStatus: Int? = null,
    @Json(name = "present") 
    val present: Boolean? = null,
    @Json(name = "present_Count") 
    val presentCount: Int? = null,
    @Json(name = "professionId") 
    val professionId: Int? = null,
    @Json(name = "profilePicture") 
    val profilePicture: String? = null,
    @Json(name = "qrCode") 
    val qrCode: Any? = null,
    @Json(name = "referenceNo") 
    val referenceNo: Any? = null,
    @Json(name = "referralCode") 
    val referralCode: Any? = null,
    @Json(name = "religionID") 
    val religionID: Int? = null,
    @Json(name = "requiredPoints") 
    val requiredPoints: Int? = null,
    @Json(name = "sfaCode") 
    val sfaCode: Any? = null,
    @Json(name = "smartPhoneUser") 
    val smartPhoneUser: Any? = null,
    @Json(name = "storeName") 
    val storeName: Any? = null,
    @Json(name = "tahasilImage") 
    val tahasilImage: Any? = null,
    @Json(name = "talukId") 
    val talukId: Int? = null,
    @Json(name = "tardy") 
    val tardy: Boolean? = null,
    @Json(name = "tardy_Count") 
    val tardyCount: Int? = null,
    @Json(name = "title") 
    val title: Any? = null,
    @Json(name = "type") 
    val type: Any? = null,
    @Json(name = "userId") 
    val userId: Int? = null,
    @Json(name = "verificationStatus") 
    val verificationStatus: Any? = null,
    @Json(name = "verifiedStatus") 
    val verifiedStatus: Int? = null,
    @Json(name = "walletNumber") 
    val walletNumber: Any? = null,
    @Json(name = "whatsAppUser") 
    val whatsAppUser: Any? = null
)*/
