package com.loyaltyworks.hrjohnson.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class CodeStatusRequest(
    @Json(name = "ActionType")
    var actionType: Int? = null,
    @Json(name = "MemberID")
    var memberID: String? = null,
    @Json(name = "QrCodeStatusID")
    var qrCodeStatusID: Int? = null,
    @Json(name = "FromDate")
    var fromDate: String? = null,
    @Json(name = "ToDate")
    var toDate: String? = null,
    @Json(name = "StartIndex")
    var startIndex: Int? = null,
    @Json(name = "PageSize")
    var pageSize: Int? = null
)

@JsonClass(generateAdapter = true)
data class CodeStatusResponse(
    @Json(name = "createdDate")
    val createdDate: Any? = null,
    @Json(name = "customerTypeCode")
    val customerTypeCode: Any? = null,
    @Json(name = "generatedCodesCount")
    val generatedCodesCount: Int? = null,
    @Json(name = "generatedFor")
    val generatedFor: Any? = null,
    @Json(name = "invoiceNo")
    val invoiceNo: Any? = null,
    @Json(name = "month")
    val month: Int? = null,
    @Json(name = "plantCode")
    val plantCode: Any? = null,
    @Json(name = "plantName")
    val plantName: Any? = null,
    @Json(name = "qrUsegereport")
    val qrUsegereport: List<QrUsegereport>? = null,
    @Json(name = "returnMessage")
    val returnMessage: Any? = null,
    @Json(name = "returnValue")
    val returnValue: Int? = null,
    @Json(name = "sCQueueID")
    val sCQueueID: Int? = null,
    @Json(name = "sku")
    val sKU: Any? = null,
    @Json(name = "scratchCodesList")
    val scratchCodesList: Any? = null,
    @Json(name = "segment")
    val segment: Any? = null,
    @Json(name = "subSegment")
    val subSegment: Any? = null,
    @Json(name = "totalRecords")
    val totalRecords: Int? = null,
    @Json(name = "totalRows")
    val totalRows: Int? = null,
    @Json(name = "usedScratchCodesList")
    val usedScratchCodesList: Any? = null,
    @Json(name = "year")
    val year: Int? = null
)

@JsonClass(generateAdapter = true)
data class QrUsegereport(
    @Json(name = "accessedDate")
    val accessedDate: Any? = null,
    @Json(name = "address")
    val address: Any? = null,
    @Json(name = "addressCount")
    val addressCount: Int? = null,
    @Json(name = "bankingBy")
    val bankingBy: String? = null,
    @Json(name = "bankingDate")
    val bankingDate: String? = null,
    @Json(name = "bankingDateFormat")
    val bankingDateFormat: Any? = null,
    @Json(name = "bankingSource")
    val bankingSource: String? = null,
    @Json(name = "brandId")
    val brandId: Int? = null,
    @Json(name = "city")
    val city: Any? = null,
    @Json(name = "codeStatusWiseCount")
    val codeStatusWiseCount: Int? = null,
    @Json(name = "country")
    val country: Any? = null,
    @Json(name = "customerType")
    val customerType: Any? = null,
    @Json(name = "distributor")
    val distributor: Any? = null,
    @Json(name = "isMember")
    val isMember: Any? = null,
    @Json(name = "lastDate")
    val lastDate: Any? = null,
    @Json(name = "latitude")
    val latitude: Any? = null,
    @Json(name = "latitudeCount")
    val latitudeCount: Int? = null,
    @Json(name = "locationName")
    val locationName: Any? = null,
    @Json(name = "longitude")
    val longitude: Any? = null,
    @Json(name = "loyaltyId")
    val loyaltyId: String? = null,
    @Json(name = "mapURL")
    val mapURL: Any? = null,
    @Json(name = "memberName")
    val memberName: Any? = null,
    @Json(name = "membershipId")
    val membershipId: Any? = null,
    @Json(name = "mobile")
    val mobile: Any? = null,
    @Json(name = "pinCode")
    val pinCode: Any? = null,
    @Json(name = "pointsawarded")
    val pointsawarded: Int? = null,
    @Json(name = "printDate")
    val printDate: Any? = null,
    @Json(name = "printDateFormat")
    val printDateFormat: Any? = null,
    @Json(name = "productId")
    val productId: Int? = null,
    @Json(name = "productName")
    val productName: Any? = null,
    @Json(name = "qRCodeStatusID")
    val qRCodeStatusID: Int? = null,
    @Json(name = "remarks")
    val remarks: Any? = null,
    @Json(name = "retailer")
    val retailer: Any? = null,
    @Json(name = "scratchCode")
    val scratchCode: String? = null,
    @Json(name = "size")
    val size: Any? = null,
    @Json(name = "sku")
    val sku: Any? = null,
    @Json(name = "state")
    val state: Any? = null,
    @Json(name = "status")
    val status: Any? = null,
    @Json(name = "thickness")
    val thickness: Any? = null,
    @Json(name = "totalCode")
    val totalCode: String? = null,
    @Json(name = "totalRows")
    val totalRows: String? = null,
    @Json(name = "transactiondate")
    val transactiondate: Any? = null,
    @Json(name = "usedBankingBy")
    val usedBankingBy: Any? = null,
    @Json(name = "usedBankingDate")
    val usedBankingDate: Any? = null,
    @Json(name = "usedBankingSource")
    val usedBankingSource: Any? = null,
    @Json(name = "usedMembershipId")
    val usedMembershipId: Any? = null,
    @Json(name = "usedRemarks")
    val usedRemarks: String? = null,
    @Json(name = "userImage")
    val userImage: Any? = null,
    @Json(name = "warehouse")
    val warehouse: Any? = null,

    var isChecked: Boolean = false
)
